// vars: presup_classes

var presup_classes = 
[['(: thank', ['positive']],
['</b> <b>says, &quot;God forgive', ['positive']],
['Condemn', ['bb']],
['abandon', ['negative']],
['abandoned', ['negative', 'bn', 'gb', 'bg', 'bb']],
['abandoned', ['bb']],
['abandoned you once she realized', ['bb']],
['abandoning', ['negative']],
['abhor', ['negative']],
['abhorred', ['bb']],
['abhorred', ['negative', 'bb']],
['about to give', ['gn']],
['absolve', ['positive']],
['absolved', ['gb']],
['abuse', ['negative', 'bg']],
['abused', ['bg']],
['abused', ['negative', 'bg']],
['abuses', ['negative']],
['abusing', ['bg']],
['accept', ['positive', 'gg', 'gn', 'gb']],
['accept', ['positive', 'bb', 'gn', 'gg', 'gg', 'gb', 'gb', 'gn', 'gn']],
['accepted', ['positive', 'gg', 'gg', 'gb', 'gb', 'gn', 'gn']],
['accepted', ['gg', 'gg', 'gb', 'gb', 'gn', 'gn']],
['accepting', ['positive', 'gn', 'gg', 'gb']],
['accepts', ['gg', 'gb', 'gb', 'gn', 'gn']],
['accepts', ['positive', 'gg', 'gn', 'gb']],
['accompanied', ['gg', 'bb']],
['according', ['positive']],
['accost', ['negative']],
['accosting', ['negative']],
['accuse', ['negative', 'gb', 'bb']],
['accused', ['bb']],
['accused', ['negative', 'bb']],
['accuses', ['negative', 'bb']],
['acknowledge', ['positive', 'gg', 'gb', 'gb', 'gn', 'gn']],
['acknowledged', ['positive', 'gg', 'gb', 'gn']],
['acknowledged', ['gg', 'gb', 'gn']],
['acknowledges', ['gg', 'gn', 'gb', 'gb']],
['acknowledges', ['positive', 'gg', 'gn', 'gb', 'gb']],
['acknowledging', ['positive']],
['acquire them and they pay', ['r']],
['actually blaming', ['bb']],
['actually charged', ['bb']],
['actually sold', ['bb']],
['administered', ['gg', 'gn', 'gb']],
['admire', ['positive', 'gg']],
['admire', ['positive', 'bg', 'bb']],
['admired', ['positive', 'gg']],
['admired', ['gg']],
['admires', ['gg']],
['admires', ['positive', 'gg']],
['admitted', ['positive', 'gg', 'gb']],
['admitted', ['gg', 'gb']],
['admonish', ['negative', 'bb']],
['admonished', ['negative', 'bb']],
['admonishes', ['negative']],
['admonishing', ['bb']],
['adore', ['positive', 'gg']],
['adored', ['gg']],
['adored', ['positive', 'gg']],
['adores', ['gg']],
['adores', ['positive', 'gg']],
['adorned', ['gg']],
['advertise', ['gg']],
['advertises', ['gg']],
['affect', ['neutral']],
['affects', ['neutral']],
['affirm', ['positive', 'gg']],
['affirmed', ['gg', 'bb']],
['aggravated', ['negative']],
['aggravating', ['negative']],
['agitated', ['negative']],
['agree', ['positive']],
['agreed', ['positive']],
['agrees', ['positive']],
['all thanked', ['gg']],
['allocate', ['gg', 'gn', 'gb']],
['allow', ['positive', 'gg']],
['allowed', ['positive']],
['allowing', ['positive']],
['allows', ['gg']],
['allows', ['positive', 'gg']],
['almost hate', ['negative', 'bb']],
['hate', ['negative', 'bb']],
['recognize', ['positive', 'negative', 'gg', 'gb', 'bb']],
['recognizes', ['positive', 'negative', 'gg', 'gb', 'bb']],
['recognized', ['positive', 'negative', 'gg', 'gb', 'bb']],
['recognizing', ['positive', 'negative', 'gg', 'gb', 'bb']],
['recognise', ['positive', 'negative', 'gg', 'gb', 'bb']],
['recognises', ['positive', 'negative', 'gg', 'gb', 'bb']],
['recognised', ['positive', 'negative', 'gg', 'gb', 'bb']],
['recognising', ['positive', 'negative', 'gg', 'gb', 'bb']],
['resents', ['bg', 'bb']],
['thank', ['positive', 'gg']],
['want to thank', ['positive', 'gg']],
['blamed', ['bb']],
['charge', ['bg', 'r']],
['reminds', ['gg', 'gb']],
['am proud of', ['gg']],
['amaze', ['positive']],
['amazed', ['positive']],
['amazes', ['positive']],
['ambush', ['negative']],
['ambushed', ['negative']],
['amuse', ['positive']],
['amused', ['positive']],
['amuses', ['positive']],
['analyzed', ['gg', 'gn', 'bb']],
['anger', ['negative']],
['angered', ['negative']],
['annihilate', ['negative']],
['annihilated', ['negative']],
['announced', ['gg']],
['annoy', ['negative']],
['annoyed', ['negative']],
['annoying', ['negative']],
['annoys', ['negative']],
['answered', ['gg', 'gn', 'gb']],
['apologize', ['gb']],
['appeal', ['positive']],
['appealed', ['positive']],
['appease', ['positive']],
['applaud', ['positive', 'gg']],
['applauded', ['gg', 'bb']],
['applauds', ['gg']],
['appointed', ['gg']],
['appraise', ['gg']],
['appreciate', ['positive', 'gg']],
['appreciated', ['gg']],
['appreciated', ['positive', 'gg']],
['appreciates', ['positive', 'gg']],
['appreciates', ['gg']],
['apprize', ['gg']],
['approach', ['gg', 'bb']],
['approached', ['gg', 'bb']],
['approve', ['positive', 'gg']],
['treating', ['positive', 'gg', 'gb']],
['are, rather than reject', ['negative']],
['arrest', ['negative', 'bg', 'bg', 'gb', 'bb', 'bb']],
['arrested', ['bg', 'bg', 'bb', 'bb']],
['arrested', ['negative', 'bg', 'bg', 'bb', 'bb']],
['arresting', ['negative', 'bg', 'bg', 'bb', 'bb']],
['arrived to thank', ['positive', 'gg']],
['ask', ['gg', 'gb']],
['asked', ['gg', 'gb']],
['asked', ['bb', 'bg', 'bb', 'bn', 'gg', 'gb']],
['asking', ['gg', 'gb']],
['asks', ['bb', 'gg', 'gb']],
['assembled', ['gg', 'gn', 'gb']],
['assess', ['neutral']],
['assessed', ['gg', 'bb']],
['assigns', ['gg', 'gn', 'gb']],
['assure', ['positive']],
['assured', ['positive']],
['astonished', ['positive']],
['attack', ['negative', 'bb']],
['attacked', ['bb']],
['attacked', ['negative', 'bb']],
['attacking', ['negative', 'bb']],
['attacking', ['bb']],
['attacks', ['bb']],
['attacks', ['negative', 'bb']],
['hates', ['negative', 'bn', 'bg', 'bb']],
['avoid', ['negative', 'bb']],
['avoided', ['negative', 'bb']],
['avoided', ['bb']],
['avoiding', ['negative', 'bb']],
['avoids', ['bb']],
['avoids', ['negative', 'bb']],
['awarding', ['positive']],
['awards', ['gg']],
['awes', ['positive']],
['axe', ['bb']],
['babbled', ['negative']],
['back', ['positive']],
['backed', ['positive']],
['backs', ['positive']],
['bag', ['bn', 'bg', 'bb', 'bb']],
['bagged', ['bn', 'bg', 'bb']],
['bait', ['negative']],
['baits', ['negative']],
['ban', ['bb']],
['banishing', ['negative']],
['banned', ['bb']],
['bans', ['bb']],
['bargained', ['gg', 'gn', 'gb']],
['bash', ['bb']],
['bashed', ['bb']],
['bashing', ['bb']],
['beat', ['negative', 'bb']],
['befriend', ['positive']],
['befriended', ['positive']],
['befriending', ['positive']],
['interviewing', ['positive', 'neutral', 'gg', 'gb', 'gn', 'nb', 'ng', 'bb']],
['begged', ['bg', 'bg', 'bb', 'bb']],
['begged', ['negative', 'bg', 'bg', 'bb', 'bb']],
['begrudge', ['bg', 'bb']],
['begrudging', ['bg', 'bb']],
['begs', ['bg', 'bb']],
['begs', ['negative', 'bg', 'bb']],
['behead', ['bb']],
['believe', ['neutral', 'gg', 'gb']],
['believed', ['neutral', 'gg', 'gb']],
['believed', ['gg', 'gb']],
['believes', ['neutral']],
['believing', ['neutral']],
['belittle', ['negative', 'bb']],
['belittles', ['negative']],
['benched', ['bb']],
['berate', ['negative', 'bb']],
['berated', ['negative', 'bb']],
['berated', ['bb']],
['berates', ['bb']],
['berates', ['negative', 'bb']],
['beseech', ['negative']],
['beseeched', ['negative']],
['besought', ['negative']],
['betray', ['negative']],
['betrayed', ['negative', 'bg', 'bn']],
['betrayed', ['bg', 'bn']],
['betraying', ['negative']],
['betrays', ['bn', 'bg', 'bb']],
['betrays', ['negative', 'bn', 'bg', 'bb']],
['bill', ['r']],
['billed', ['r']],
['billing', ['r', 'bg', 'bb']],
['bills', ['r']],
['bites', ['bg', 'bb', 'bb']],
['blame', ['negative', 'bb']],
['blame', ['negative', 'gb']],
['blamed', ['negative', 'bb']],
['blamed', ['bb']],
['blames', ['negative', 'bb']],
['blames', ['bb']],
['blaming', ['bb']],
['blasphemes', ['bb']],
['blast', ['bb']],
['blasted', ['bb']],
['bleed', ['negative']],
['bleeds', ['negative']],
['bless', ['positive', 'gg']],
['blessed', ['positive', 'gg']],
['blessed', ['gg']],
['blesses', ['positive', 'gg']],
['blesses', ['gg']],
['blessing', ['positive']],
['blister', ['negative']],
['block', ['negative']],
['blocked', ['bb']],
['blocked', ['negative', 'bb']],
['blocks', ['negative']],
['bollocked', ['bb']],
['bomb', ['negative']],
['bombed', ['negative']],
['bombing', ['negative']],
['boo', ['bb']],
['book', ['gg', 'gb']],
['booked', ['gg', 'gb']],
['bore', ['negative', 'gg', 'gb']],
['bored', ['negative']],
['bores', ['negative']],
['both resent', ['negative', 'bg', 'bb']],
['bother', ['negative']],
['bothering', ['negative']],
['bought', ['gg', 'r']],
['break', ['negative']],
['breaking', ['negative']],
['bribe', ['bb', 'bg']],
['bring', ['gg', 'gb']],
['broke', ['negative', 'bb']],
['brought', ['gg', 'gb']],
['brought with', ['gg', 'gn', 'gb']],
['bug', ['negative', 'bn', 'bg', 'bb']],
['bugging', ['negative']],
['bugs', ['negative']],
['bullying', ['negative', 'bg', 'bb', 'bn']],
['bullies', ['negative', 'bg', 'bb', 'bn']],
['burn', ['negative', 'bb']],
['burns', ['negative', 'bb']],
['burned', ['negative', 'bb']],
['burnt', ['negative', 'bb']],
['burning', ['negative', 'bb']],
['bury', ['bb']],
['busted', ['bb']],
['busting', ['bb']],
['buy', ['gg', 'r']],
['call for', ['gg', 'nb', 'ng', 'bb']],
['call', ['positive', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['called', ['positive', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['calls', ['positive', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['calling', ['positive', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['phone', ['positive', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['phones', ['positive', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['phoned', ['positive', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['phoning', ['positive', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['can', ['negative', 'bb']],
['accept', ['positive', 'gg', 'gn', 'gb']],
['blame', ['negative', 'bb']],
['forgive', ['positive', 'gb']],
['give', ['gg', 'bb']],
['can never forgive', ['positive', 'bb']],
['can only give a thank you to', ['gg', 'bg']],
['can start enjoying', ['gg']],
['can thank', ['positive', 'gg']],
['~blame', ['gb']],
['~fault', ['gb']],
['~forgive', ['bb']],
['cancel', ['bb']],
['cannot believe I volunteered', ['bb']],
['~fault', ['positive', 'gb']],
['~forgive', ['negative', 'bb']],
['~marry', ['bb']],
['~pardon', ['negative', 'bb']],
['~retaliate', ['gb', 'bb']],
['captivate', ['positive']],
['care', ['positive']],
['cared', ['positive']],
['cares', ['positive']],
['carries', ['gg', 'gb']],
['carry', ['positive', 'gg', 'gb']],
['cast', ['gg', 'bb']],
['casted', ['gg', 'bb']],
['castigate', ['negative', 'bb']],
['catch', ['bb']],
['caught', ['bb']],
['celebrate', ['positive', 'gg']],
['celebrated', ['gg']],
['censured', ['bb']],
['censures', ['bb']],
['challenge', ['negative', 'bb']],
['challenged', ['bb']],
['challenges', ['bb']],
['charge', ['r', 'gb', 'bb', 'bg', 'r']],
['charged', ['bb']],
['charged', ['bg', 'r', 'gb', 'bb', 'bb']],
['charges', ['r', 'bb']],
['charging', ['r', 'bb']],
['charm', ['positive']],
['charmed', ['positive']],
['chasing', ['bb']],
['chastise', ['negative', 'bb']],
['chastised', ['bb']],
['chastised', ['negative', 'bb']],
['chastises', ['negative']],
['chastising', ['negative']],
['check', ['gg', 'gb']],
['checked', ['gg', 'gb']],
['cheer', ['positive']],
['cheered', ['positive']],
['cherish', ['positive', 'gg']],
['cherished', ['gg']],
['cherished', ['positive', 'gg']],
['cherishes', ['gg']],
['cherishing', ['positive']],
['chewed', ['bb']],
['chided', ['bb']],
['chided', ['negative', 'bb']],
['choke', ['negative']],
['choked', ['negative']],
['choose', ['gg', 'bb']],
['chooses', ['gg', 'bb']],
['chose', ['gg', 'bb', 'nb', 'ng']],
['cite', ['gg', 'bb']],
['cited', ['gg', 'bb']],
['claimed', ['gg', 'gn', 'gb']],
['cleansing', ['positive']],
['clocked', ['r', 'bb', 'bb']],
['clowned', ['bb']],
['coached', ['gg', 'gn', 'gb']],
['comdemn', ['bb']],
['comfort', ['positive']],
['comforted', ['positive', 'gb']],
['comforted', ['gb']],
['comforting', ['positive']],
['commend', ['positive', 'gg']],
['commended', ['gg']],
['commends', ['gg']],
['commiserated', ['negative']],
['comped', ['gn', 'gb']],
['compensate', ['positive', 'gg', 'r', 'gb']],
['compensated', ['r']],
['compensates', ['r']],
['complain', ['negative']],
['complained', ['negative']],
['complement', ['positive']],
['complemented', ['positive']],
['complements', ['positive']],
['compliment', ['positive', 'gg']],
['complimented', ['gg']],
['complimented', ['positive', 'gg']],
['complimenting', ['positive']],
['compliments', ['positive']],
['condemn', ['negative', 'bb']],
['condemned', ['bb']],
['condemning', ['bb']],
['condemns', ['bb']],
['condone', ['positive', 'gb']],
['confront', ['negative', 'gb', 'bb']],
['confronted', ['bb']],
['confronted', ['negative', 'bb']],
['confronting', ['negative']],
['confronts', ['negative']],
['confuse', ['negative']],
['congratulate', ['positive', 'gg']],
['congratulated', ['positive', 'gg', 'gg']],
['congratulated', ['gg', 'gg']],
['congratulates', ['positive', 'gg']],
['congratulates', ['gg']],
['conquer', ['positive']],
['conquered', ['positive']],
['consider', ['neutral', 'gg', 'gn', 'gb']],
['considered', ['gg', 'gn', 'gb']],
['considering', ['gg', 'gn', 'gb']],
['considering', ['neutral', 'gg', 'gn', 'gb']],
['considers', ['gg', 'gn', 'gb']],
['console', ['positive']],
['conspire', ['negative']],
['constantly admonished', ['bb']],
['constrained', ['negative']],
['consume', ['negative']],
['consumed', ['negative']],
['contact', ['gg', 'bb', 'nn', 'nb', 'ng']],
['contacted', ['gg', 'bb', 'nb', 'ng', 'nn']],
['contemplate', ['neutral']],
['contradict', ['negative']],
['contradicting', ['negative']],
['controlled', ['bg', 'bn']],
['convicted', ['bb']],
['convince', ['positive']],
['convinces', ['positive']],
['convincing', ['positive']],
['cooperated', ['positive']],
['could ask', ['gg', 'gb']],
['could ever repay', ['positive']],
['could fault', ['negative', 'bb']],
['could forgive', ['positive', 'gb']],
['could have prepared her', ['ng', 'bb']],
['could leave', ['bb']],
['could never forgive', ['positive', 'bb']],
['could never repay', ['positive', 'bg']],
['could pay', ['gg']],
['could prepare', ['gn', 'gg', 'gb']],
['could sue', ['bb']],
['could thank', ['positive', 'gg']],
['could to prepare', ['gg', 'gn', 'gb']],
['courted', ['positive']],
['cover', ['gg', 'gb']],
['craved', ['positive']],
['craves', ['ng']],
['created', ['bb', 'gg', 'gb', 'gn']],
['credit', ['gg', 'gg', 'r', 'r']],
['credited', ['gg', 'r']],
['credits', ['gg', 'r']],
['cried', ['negative']],
['cries', ['negative']],
['criticise', ['bb']],
['criticises', ['bb']],
['criticising', ['bb']],
['criticize', ['negative', 'bb']],
['criticized', ['bb']],
['criticizes', ['bb']],
['criticizing', ['bb']],
['cross', ['bb']],
['crucified', ['bg', 'bb']],
['crucify', ['bb']],
['crucifying', ['bb']],
['cry', ['negative']],
['cryed', ['negative']],
['cuff', ['bb']],
['curse', ['negative', 'bb']],
['cursed', ['bb']],
['cursed', ['negative', 'bb']],
['curses', ['bb']],
['curses', ['negative', 'bb']],
['cursing', ['negative']],
['cut', ['negative', 'bb']],
['cutting', ['negative']],
['accept', ['positive', 'gg', 'gn', 'gb']],
['appreciate', ['positive', 'gg']],
['be suing', ['bb']],
['better hate', ['negative', 'bb']],
['blame', ['negative', 'bb']],
['expose', ['negative', 'gb', 'bb']],
['forgive', ['positive', 'gb']],
['forgiven', ['gb']],
['holla at', ['gg', 'nb', 'ng', 'bb']],
['love', ['positive', 'gg']],
['love to have', ['gg']],
['milk', ['bg', 'bn']],
['never forgive', ['positive', 'bb']],
['nominate', ['gg']],
['smack', ['negative', 'bb']],
['smacks', ['negative', 'bb']],
['smacked', ['negative', 'bb']],
['smacking', ['negative', 'bb']],
['thank', ['positive', 'gg']],
['damaging', ['negative']],
['damn', ['negative', 'bb']],
['dared', ['positive']],
['daring', ['positive']],
['dashed', ['negative']],
['dazzle', ['positive']],
['dazzled', ['positive']],
['dazzles', ['positive']],
['deceive', ['negative']],
['deceived', ['negative']],
['deceiving', ['negative']],
['deck', ['bb']],
['decline', ['negative']],
['defeat', ['negative']],
['defeated', ['negative']],
['defend', ['positive', 'gg', 'gb']],
['defends', ['positive', 'gg', 'gb']],
['defended', ['positive', 'gg', 'gb']],
['defending', ['positive', 'gg', 'gb']],
['defy', ['negative', 'bb']],
['defies', ['negative', 'bb']],
['defied', ['negative', 'bb']],
['defying', ['negative', 'bb']],
['define', ['bb', 'bn', 'gg']],
['defined', ['gg', 'bn', 'bb']],
['defy', ['negative']],
['defying', ['negative']],
['degrade', ['negative']],
['deleted', ['bb']],
['deluded', ['negative']],
['demand', ['both']],
['demonize', ['negative']],
['demoted', ['bb']],
['denied', ['negative', 'bb']],
['denied', ['bb']],
['denounce', ['negative', 'bb']],
['denounced', ['bb']],
['denounces', ['negative', 'bb']],
['denounces', ['bb']],
['deny', ['negative', 'bg', 'bb']],
['denying', ['negative']],
['deplored', ['bb']],
['depress', ['negative']],
['deserted', ['negative', 'bb']],
['deserts', ['negative', 'bb']],
['deserve', ['positive']],
['deserved', ['positive']],
['deserves', ['gg', 'bb']],
['deserves', ['positive', 'gg', 'bb']],
['desire', ['positive']],
['desired', ['positive']],
['desires', ['positive']],
['despise', ['negative', 'bb']],
['despised', ['negative', 'bb']],
['despised', ['bb']],
['despises', ['negative', 'bb']],
['despises', ['bb']],
['despising', ['negative']],
['destroy', ['negative', 'bb']],
['destroyed', ['negative']],
['destroying', ['negative']],
['destroys', ['negative']],
['detest', ['negative', 'bb']],
['detested', ['bb']],
['detests', ['bb']],
['did come to forgive', ['positive', 'gb']],
['did hire', ['gg', 'gn', 'gb']],
['did not charge', ['gg', 'gb']],
['did not recognize', ['bg', 'bn']],
['did warn', ['gb']],
["didn't blame", ['negative', 'gb']],
["didn't charge", ['gg', 'gb']],
["didn't scold", ['negative', 'gb']],
['dig', ['positive', 'gg']],
['dis', ['bb']],
['disagree', ['negative']],
['disagreed', ['negative']],
['disagrees', ['negative']],
['disappoint', ['negative']],
['disappointed', ['negative']],
['disbelieve', ['negative']],
['disbelieved', ['negative']],
['discipline', ['bb']],
['disciplines', ['bb']],
['discouraged', ['negative']],
['discover', ['gg', 'bb']],
['discovered', ['gg', 'bb']],
['discredit', ['negative', 'bb']],
['discredited', ['bg', 'bb']],
['discriminate', ['negative']],
['disemboweled', ['bb']],
['disgrace', ['negative']],
['disgruntle', ['negative']],
['disgust', ['negative']],
['disgusted', ['negative', 'bb']],
['disgusted', ['bb']],
['disillusioning', ['negative']],
['disinclude', ['bb']],
['dislike', ['negative', 'bb']],
['disliked', ['bb']],
['dislikes', ['bb']],
['dismiss', ['bn', 'bb']],
['dismissed', ['bn', 'bb']],
['disobey', ['negative']],
['disobeyed', ['negative']],
['disobeying', ['negative']],
['disobeys', ['negative']],
['disowned', ['negative']],
['disowning', ['negative']],
['disparaged', ['negative']],
['displease', ['negative']],
['disputes', ['bb']],
['disqualify', ['bb']],
['disrespect', ['negative', 'bb']],
['disrespected', ['negative']],
['disrespects', ['negative', 'bb']],
['disrespects', ['bb']],
['diss', ['bb']],
['dissed', ['bb']],
['dissuade', ['negative']],
['distracting', ['negative']],
['distressed', ['negative']],
['distressing', ['negative']],
['distrust', ['negative']],
['distrusted', ['negative']],
['distrusting', ['negative']],
['disturb', ['negative']],
['disturbed', ['negative']],
['disturbing', ['negative']],
['disturbs', ['negative']],
['ditch', ['bb']],
['ditched', ['bb']],
['ditches', ['bb']],
['do accept', ['positive', 'gb']],
['do forgive', ['positive', 'gb']],
['do like', ['positive', 'gg']],
['do love', ['positive', 'gg']],
['do not mistake', ['gg', 'bb']],
['do owe', ['gg', 'bg', 'r', 'gb', 'bb']],
['do recognize', ['gg', 'gb', 'bb']],
['docked', ['bb']],
['doctored', ['gb']],
['does forgive', ['positive', 'gb']],
['does not hate', ['negative', 'gb']],
["doesn't resent", ['negative', 'gg', 'gb']],
["don't admire", ['positive', 'bg', 'bb']],
["don't blame", ['negative', 'gb']],
["don't forgive", ['positive', 'bb']],
["don't judge", ['gb']],
["don't just want", ['positive', 'gg', 'gb', 'bb']],
['dote', ['positive']],
['dotes', ['positive']],
['doubt', ['negative']],
['doubted', ['negative']],
['doubting', ['negative']],
['drafted', ['bb']],
['dread', ['negative']],
['drilling', ['bg', 'bb']],
['drop', ['bb']],
['dropped', ['bb']],
['drops', ['bb']],
['dug', ['gg']],
['dump', ['bb']],
['dumped', ['bb']],
['dumps', ['bb']],
['duped', ['negative']],
['educating', ['positive', 'gg', 'gn', 'gb']],
['elect', ['gg']],
['elected', ['gg']],
['eliminate', ['negative', 'bb']],
['eliminated', ['bg']],
['eliminated', ['negative', 'bg']],
['eliminating', ['negative']],
['email', ['positive', 'negative', 'neutral', 'bb', 'nb', 'ng', 'gg']],
['emasculates', ['negative']],
['embarrass', ['negative']],
['embarrassed', ['negative']],
['embarrasses', ['negative']],
['embarrassing', ['negative']],
['embrace', ['positive', 'gg']],
['embraced', ['gg']],
['embraced', ['positive', 'gg']],
['embraces', ['positive']],
['embracing', ['positive']],
['employ', ['gg']],
['employed', ['gg']],
['empower', ['positive']],
['empowering', ['positive']],
['empowers', ['gg']],
['empowers', ['positive', 'gg']],
['enabling', ['positive']],
['encourage', ['positive']],
['encouraged', ['gg']],
['encouraged', ['positive', 'gg']],
['encouraging', ['positive']],
['endangering', ['negative']],
['endangers', ['negative']],
['endorsed', ['positive']],
['energize', ['positive']],
['engage', ['neutral', 'gg', 'bb']],
['engaged', ['neutral']],
['engages', ['neutral']],
['enhance', ['positive']],
['enjoy', ['positive', 'gg']],
['enjoyed', ['gg']],
['enjoying', ['gg']],
['enlightening', ['positive']],
['enliven', ['positive']],
['ennoble', ['positive']],
['enraged', ['negative']],
['enrich', ['positive']],
['enriched', ['positive']],
['enroll with', ['gg']],
['enslave', ['negative']],
['ensues', ['bb']],
['entertain', ['positive']],
['entertained', ['positive']],
['entices', ['positive']],
['entreating', ['positive']],
['envied', ['bg']],
['envies', ['negative', 'bg']],
['envies', ['bg']],
['envision', ['positive', 'gg', 'bb']],
['envy', ['negative', 'bg']],
['equip', ['gg', 'gn', 'gb']],
['equipping', ['gg', 'gn', 'gb']],
['equips', ['gg', 'gb', 'gn']],
['esteem', ['positive']],
['evade', ['negative']],
['evaded', ['negative']],
['evaluate', ['neutral', 'gg', 'nb', 'gb', 'ng']],
['even irrationally blames', ['bb']],
['eventually sees', ['bb']],
['evict', ['bb']],
['exalt', ['positive']],
['exalts', ['positive']],
['examine', ['gb']],
['examined', ['gb']],
['exasperated', ['negative']],
['except', ['gn', 'gg', 'gb']],
['excepted', ['gg', 'gb', 'gn']],
['excited', ['positive']],
['excites', ['positive']],
['exclude', ['negative']],
['excluded', ['negative']],
['excommunicate', ['bb']],
['excoriated', ['bb']],
['excuse', ['positive', 'gb']],
['excused', ['gb']],
['excusing', ['positive']],
['execute', ['bb']],
['exhilarate', ['positive']],
['expel', ['negative']],
['expelled', ['negative']],
['experience', ['nb', 'ng']],
['exploit', ['negative', 'gn', 'bg']],
['exploited', ['negative']],
['exploiting', ['negative']],
['expose', ['negative', 'bg', 'gb', 'bb']],
['exposed', ['gg', 'gb', 'gb', 'bb', 'gb']],
['exposes', ['gb', 'bb']],
['exposing', ['negative', 'gb', 'bb']],
['exposing', ['bg', 'gb', 'bb']],
['exterminate', ['negative']],
['eyes', ['bg', 'bb']],
['faces', ['bb']],
['fail', ['negative', 'bg']],
['fail to recognize', ['bg', 'bn']],
['failed', ['negative', 'bg']],
['failed', ['bg']],
['failing', ['negative']],
['fails', ['negative']],
['fascinate', ['positive']],
['fascinates', ['positive']],
['fault', ['negative', 'bb']],
['faulted', ['bb']],
['faults', ['bb']],
['favored', ['positive']],
['fawn', ['both']],
['fear', ['negative', 'bb']],
['feared', ['bb']],
['feared', ['negative', 'bb']],
['feares', ['negative']],
['fearing', ['negative']],
['fears', ['bb']],
['fears', ['negative', 'bb']],
['feasted', ['gg']],
['fed', ['gg', 'gb']],
['feed', ['gg', 'gb']],
['feeding', ['gg', 'gb']],
['feel', ['gb']],
['feel has prepared', ['gg', 'gn', 'gb']],
['feel like it prepared', ['gg', 'gn', 'gb']],
['feel suits', ['gg']],
['filmed', ['gg', 'gb']],
['films', ['gg', 'gb']],
['finally sees', ['gg', 'bb']],
['find', ['gg', 'bb']],
['finds', ['gg', 'gb']],
['fine', ['negative', 'bb']],
['fined', ['bb']],
['fines', ['negative']],
['fining', ['negative']],
['finished', ['bb']],
['fire', ['bb']],
['fired', ['bb']],
['fit', ['gg', 'gn']],
['fitted', ['gg', 'gb', 'gn']],
['fitting', ['gg', 'gn', 'gb']],
['flame', ['bb']],
['flamed', ['bb']],
['flatter', ['positive']],
['flirt', ['negative']],
['flirts', ['negative']],
['floored', ['neutral']],
['flout', ['negative']],
['follow', ['positive', 'gg']],
['follows', ['positive', 'gg']],
['followed', ['positive', 'gg']],
['following', ['positive', 'gg']],
['forbid', ['negative', 'bb']],
['forbids', ['negative', 'bb']],
['forbid', ['negative', 'bb']],
['forbidding', ['negative', 'bb']],
['forbad', ['negative', 'bb']],
['forgave', ['positive', 'gb']],
['forget', ['negative']],
['forgets', ['negative']],
['forgetting', ['negative']],
['forgive', ['positive', 'gg', 'gb']],
['forgive', ['positive', 'bb']],
['forgiven', ['gg', 'gb']],
['forgives', ['gb']],
['forgives', ['positive', 'gb']],
['forgiving', ['positive']],
['forgot', ['negative']],
['forsake', ['negative']],
['forsook', ['negative']],
['fought', ['bb']],
['fouled', ['negative']],
['fouls', ['negative']],
['found', ['gg', 'bb']],
['frame', ['bn']],
['framed', ['bb']],
['freak', ['negative']],
['frighten', ['negative']],
['frightened', ['negative']],
['frightens', ['negative', 'bb']],
['frustrate', ['negative']],
['fry', ['bb']],
['fully accepts', ['gg', 'gn', 'gb']],
['fund', ['gg', 'gn']],
['gave', ['bb', 'gg', 'bn', 'gg', 'r', 'gb', 'gn', 'gb']],
['gave into', ['bb']],
['gawked', ['negative']],
['get', ['gg', 'gb', 'bb', 'bb']],
['gets', ['gg', 'gb', 'bb']],
['give', ['bg', 'bb', 'bn', 'gg', 'gb', 'gb', 'gn']],
['give thanks to', ['gg']],
['given', ['gg', 'gn', 'bn', 'gb', 'bb']],
['gives', ['gg', 'gb', 'bb', 'gn', 'bn']],
['giving', ['gg', 'r', 'gb', 'bb', 'gn', 'bn']],
['gladly pay', ['gg']],
['glared', ['negative']],
['glimpsed', ['gg', 'bb']],
['glorify', ['positive', 'gg']],
['goad', ['negative']],
['goads', ['negative']],
['gonna sue', ['bb']],
['goofs', ['negative']],
['gossip', ['negative']],
['got', ['gg', 'gb', 'bb', 'bb']],
['gotta admire', ['positive', 'gg']],
['grab', ['gg', 'gb', 'bb']],
['grabbed', ['gg', 'gb', 'bb']],
['greet', ['positive']],
['greeted', ['positive']],
['greeting', ['positive']],
['greets', ['positive', 'gg']],
['greets', ['gg']],
['grew up prepared', ['gg', 'gn', 'gb']],
['grieve', ['negative']],
['groomed', ['gg']],
['ground', ['bb']],
['grounded', ['bb']],
['growled', ['negative']],
['growls', ['negative']],
['grudge', ['bb']],
['guarantee', ['positive']],
['guide', ['positive', 'gg', 'gn', 'gb']],
['guides', ['positive', 'gg', 'gn', 'gb']],
['guided', ['positive', 'gg', 'gn', 'gb']],
['guiding', ['positive', 'gg', 'gn', 'gb']],
['had', ['gg', 'gn']],
['had accepted', ['gg', 'gn', 'gb']],
['had arranged for', ['gg']],
['had contacted', ['nb', 'ng', 'nn']],
['had dogs chasing', ['bb']],
['had forgiven', ['gb']],
['had paid', ['r']],
['had to do what <b>we did. Please forgive', ['positive']],
['had to respect', ['positive', 'gg', 'bg']],
['had to revive him and they prepared', ['r']],
['had with', ['gg', 'gn', 'gb']],
['hail', ['positive']],
['hailed', ['positive', 'gg']],
['hailed', ['gg']],
['hammer', ['bb']],
['hang', ['bb']],
['harangue', ['negative']],
['harangues', ['negative']],
['harass', ['negative', 'gn', 'gb']],
['harassed', ['negative']],
['harassing', ['negative']],
['has', ['gg', 'gb', 'gn', 'gg', 'gn']],
['has admired', ['gg']],
['has forgiven', ['gb']],
['has prepared', ['gg', 'gn', 'gb']],
['hate', ['negative', 'bb', 'bg']],
['hated', ['negative']],
['hated', ['bb']],
['hates', ['negative', 'bn', 'bg', 'bb']],
['hates', ['nb', 'bb']],
['hating', ['negative', 'bb']],
['haunt', ['negative']],
['haunted', ['negative']],
['have', ['gg', 'gb', 'gn']],
['have forgiven', ['gb']],
['have paid', ['r']],
['have refunded', ['r']],
['have today, and please forgive', ['positive']],
['headquartered', ['gg', 'gn', 'gb']],
['hear', ['positive', 'neutral', 'gg', 'gb', 'gn']],
['heard', ['gg', 'gn', 'gb']],
['heart', ['gg']],
['heckle', ['negative']],
['heckled', ['negative']],
['heckles', ['negative']],
['held', ['gb', 'bb']],
['help', ['positive', 'gg', 'gb', 'gb', 'gn']],
['helped', ['positive']],
['helping', ['positive']],
['helps', ['positive']],
['highlighting', ['positive']],
['highly commend', ['positive', 'gg']],
['hire', ['gg', 'gn', 'gb']],
['hired', ['gg', 'gn', 'gb']],
['hires', ['gg']],
['hiring', ['gg', 'gn', 'gb']],
['hit', ['bb']],
['hits', ['bb']],
['hold', ['gb', 'bb']],
['holds', ['gb', 'bb']],
['honor', ['positive', 'gg']],
['honored', ['gg']],
['honored', ['positive', 'gg']],
['honoring', ['positive']],
['honors', ['gg']],
['honors', ['positive', 'gg']],
['honour', ['gg']],
['honoured', ['gg']],
['hope', ['positive']],
['hope prepares', ['gg', 'gn', 'gb']],
['hope they kill', ['negative', 'bb']],
['hope you like', ['positive', 'gg']],
['hoped', ['positive']],
['horrified', ['negative']],
['hound', ['bb']],
['hounded', ['bb']],
['hugged', ['gg']],
['humble', ['positive']],
['humbling', ['positive', 'nb', 'bb']],
['humbling', ['nb', 'bb']],
['humiliate', ['negative', 'bb']],
['humiliated', ['negative']],
['humiliating', ['negative']],
['humoring', ['positive']],
['hunting', ['bn', 'bg', 'bb']],
['hurt', ['negative', 'bb']],
['hurted', ['negative']],
['hurting', ['negative']],
['hurts', ['bb']],
['hurts', ['negative', 'bb']],
['hypocritically ostracize', ['negative', 'bg']],
['identified', ['gg', 'bb']],
['identify', ['gg', 'bb']],
['identifying', ['bb']],
['idolise', ['positive', 'gg']],
['idolises', ['positive', 'gg']],
['idolised', ['positive', 'gg']],
['idolising', ['positive', 'gg']],
['idolize', ['positive', 'gg']],
['idolizes', ['positive', 'gg']],
['idolized', ['positive', 'gg']],
['idolizing', ['positive', 'gg']],
['ignore', ['negative']],
['ignored', ['negative', 'bb']],
['ignored', ['bb']],
['ignores', ['negative']],
['ignoring', ['bb']],
['ignoring', ['negative', 'bb']],
['illumine', ['positive']],
['illumines', ['positive']],
['implore', ['both']],
['imply', ['neutral']],
['importuned', ['negative']],
['incarcerate', ['bb']],
['inciting', ['negative']],
['indict', ['bb']],
['indicts', ['bb']],
['inflicted', ['negative']],
['informed', ['gg', 'gn', 'gb']],
['infuriate', ['negative']],
['infuriated', ['negative']],
['infuriates', ['negative']],
['injure', ['negative']],
['injuring', ['negative']],
['inspire', ['positive']],
['inspired', ['positive']],
['inspires', ['positive']],
['inspiring', ['positive']],
['instantly recognizes', ['gg', 'gb', 'bb']],
['insult', ['negative', 'bb']],
['insulted', ['negative']],
['insulting', ['negative']],
['insults', ['negative']],
['intended', ['gg', 'gn', 'gb']],
['interest', ['positive']],
['interested', ['positive']],
['interests', ['positive']],
['interfere', ['negative']],
['interrupting', ['negative']],
['interviewed', ['positive', 'neutral', 'gg', 'gb', 'gn', 'nb', 'ng', 'bb']],
['intimidating', ['bb']],
['intrigue', ['neutral']],
['intrigued', ['neutral']],
['intrigues', ['neutral']],
['invite', ['gg']],
['invites', ['gg']],
['invoice', ['r']],
['irks', ['negative']],
['irritate', ['negative']],
['irritated', ['negative']],
['irritates', ['negative']],
['is blaming', ['bb']],
['is playing', ['bg', 'bb']],
['is selling', ['gg', 'r']],
['isolate', ['negative']],
['isolated', ['bb']],
['jeers to', ['bg', 'bb']],
['jilted', ['bb']],
['join', ['positive', 'gg']],
['joined', ['positive', 'gg']],
['joining', ['positive', 'gg']],
['joins', ['positive', 'gg']],
['rejoin', ['positive', 'gg']],
['rejoined', ['positive', 'gg']],
['rejoining', ['positive', 'gg']],
['rejoins', ['positive', 'gg']],
['joke', ['positive']],
['joked', ['positive']],
['judge', ['bg', 'bn']],
['judged', ['bg', 'bb']],
['judges', ['gg', 'gb']],
['judging', ['bn', 'bg', 'bb']],
['just love', ['positive', 'gg', 'bg']],
['just mistook', ['bg', 'bb']],
['just thanking', ['gg']],
['just used', ['bn', 'ng']],
['just wanted to say a great big "Thank you" to', ['gg']],
['justifies', ['positive']],
['keep', ['gg', 'gn', 'gb']],
['keep exposing', ['gb', 'bb']],
['kept', ['gg', 'gb', 'gn']],
['kept billing', ['bg', 'r']],
['kid', ['positive']],
['kidded', ['positive']],
['kill', ['negative', 'bb']],
['killed', ['bb']],
['killed', ['negative', 'bb']],
['killing', ['negative', 'bb']],
['killing', ['bb']],
['kills', ['negative', 'bb']],
['kills', ['bb']],
['kiss', ['positive']],
['kissed', ['gg']],
['kissed', ['positive', 'gg']],
['kisses', ['positive']],
['knew', ['neutral', 'gg', 'nb', 'ng', 'bb']],
['knifed', ['negative']],
['knock', ['negative', 'bb']],
['knocks', ['bb']],
['know', ['neutral', 'gg', 'bb', 'nb', 'ng']],
['know has qualified', ['gg']],
['know it frightens', ['bb']],
['knowing', ['gg', 'nb', 'ng', 'bb']],
['knows', ['neutral', 'gg', 'bb', 'bb', 'nb', 'ng']],
['knows', ['gg', 'bb', 'bb', 'nb', 'ng']],
['knows he needs', ['bn', 'bg', 'bb']],
['labeled', ['bn', 'bg', 'bb']],
['labels', ['bn', 'bg', 'bb']],
['lambasted', ['bb']],
['lambasts', ['bb']],
['lamented', ['bb']],
['lapidate', ['bb']],
['laud', ['positive', 'gg']],
['lauded', ['gg']],
['laugh', ['negative']],
['laughed', ['negative']],
['laughs', ['negative']],
['lays into', ['bb']],
['leaves', ['bb']],
['leaving', ['bb']],
['lectures', ['bb']],
['lectures', ['negative', 'bb']],
['left', ['nb', 'bb']],
['lent', ['r']],
['liberated', ['positive']],
['liberating', ['positive']],
['like', ['positive', 'gg', 'gn', 'gb']],
['always love', ['positive', 'gg']],
['behead', ['bb']],
['challenge', ['negative', 'bn', 'bg', 'bb']],
['cover', ['gb']],
['dump', ['bb']],
['fit', ['gg', 'gn']],
['forgive', ['positive', 'gb']],
['hang', ['bb']],
['hate', ['negative', 'bb']],
['invoice', ['r']],
['kill', ['negative', 'bb']],
['leave', ['bb']],
['like', ['positive', 'gg']],
['pay', ['r']],
['resent', ['negative', 'bb']],
['respect', ['positive', 'gg']],
['reward', ['positive', 'gg']],
['schedule', ['gg', 'gb']],
['stay with', ['gg']],
['take', ['gg', 'bg', 'gb', 'bb']],
['thank', ['positive', 'gg']],
['train', ['gg', 'gn', 'gb']],
['loathe', ['negative']],
['loathed', ['negative']],
['loathes', ['negative']],
['longed', ['negative']],
['love', ['positive', 'gg']],
['loved', ['positive', 'gg']],
['loveed', ['positive']],
['lovees', ['positive']],
['loveing', ['positive']],
['loves', ['positive']],
['loving', ['positive', 'gg']],
['luring', ['negative']],
['m proud of', ['gg']],
['manipulate', ['negative']],
['manipulated', ['negative']],
['manipulates', ['negative']],
['marry', ['positive', 'gg']],
['married', ['positive', 'gg']],
['matter', ['neutral']],
['mattered', ['neutral']],
['mean', ['neutral']],
['meant', ['neutral']],
['meddled', ['negative']],
['mesmerized', ['positive']],
['mind', ['negative']],
['ministered', ['positive']],
['misbehave', ['negative']],
['misjudged', ['negative']],
['mislead', ['negative']],
['misleading', ['negative']],
['misled', ['negative']],
['misunderstand', ['negative']],
['misunderstands', ['negative']],
['misunderstood', ['negative']],
['mock', ['negative']],
['mocked', ['negative']],
['mocking', ['negative']],
['mocks', ['negative']],
['molesting', ['negative']],
['mooned', ['negative']],
['mooning', ['negative']],
['motivate', ['positive']],
['motivated', ['positive']],
['motivates', ['positive']],
['murdered', ['negative']],
['murders', ['negative']],
['nag', ['negative']],
['nagged', ['negative']],
['nagging', ['negative']],
['nags', ['negative']],
['nauseate', ['negative']],
['need', ['neutral']],
['needed', ['neutral']],
['needing', ['neutral']],
['needs', ['neutral', 'bn', 'bg', 'bb']],
['neglect', ['negative']],
['neglected', ['negative']],
['neglecting', ['negative']],
['neglects', ['negative']],
['nourish', ['positive']],
['nourished', ['positive']],
['nourishes', ['positive']],
['nurture', ['positive']],
['nurtured', ['positive']],
['obey', ['positive']],
['obeyed', ['positive']],
['obeying', ['positive']],
['obeys', ['positive']],
['obsess', ['negative']],
['offend', ['negative']],
['offended', ['negative']],
['offending', ['negative']],
['offends', ['negative']],
['oppose', ['negative']],
['opposed', ['negative']],
['opposes', ['negative']],
['oppress', ['negative']],
['overlook', ['negative']],
['overlooked', ['negative']],
['owe', ['negative', 'gg', 'bg', 'r', 'gb', 'bb']],
['owes', ['negative', 'gg', 'bg', 'r', 'gb', 'bb']],
['owed', ['negative', 'gg', 'bg', 'r', 'gb', 'bb']],
['owing', ['negative', 'gg', 'bg', 'r', 'gb', 'bb']],
['pacify', ['neutral']],
['paid', ['r']],
['pain', ['negative']],
['pamper', ['positive']],
['pampered', ['positive']],
['pampers', ['positive']],
['pardon', ['positive', 'bb']],
['pardoning', ['positive']],
['patronized', ['negative']],
['pay', ['gg']],
['paying', ['r']],
['persecuted', ['negative']],
['persecutes', ['negative']],
['persevere', ['positive']],
['perseveres', ['positive']],
['persuades', ['positive']],
['pinch', ['negative']],
['pinched', ['negative']],
['pinches', ['negative']],
['pitied', ['negative']],
['pities', ['negative']],
['pitying', ['negative']],
['pleaded', ['both']],
['pleads', ['both']],
['please', ['positive']],
['pleased', ['positive']],
['pleases', ['positive']],
['pleasing', ['positive']],
['praise', ['positive']],
['praised', ['positive']],
['praises', ['positive']],
['praising', ['positive']],
['pray', ['neutral']],
['prayed', ['neutral']],
['prays', ['neutral']],
['preaching', ['positive']],
['prejudging', ['negative']],
['preparing', ['gg', 'gb', 'gn']],
['prospered', ['positive']],
['protect', ['positive']],
['protected', ['positive']],
['protecting', ['positive']],
['protects', ['positive']],
['protested', ['negative']],
['provoke', ['negative']],
['provoked', ['negative']],
['provokes', ['negative']],
['provoking', ['negative']],
['qualify', ['positive']],
['quarrels', ['negative']],
['quit', ['negative']],
['raged', ['negative']],
['rallied', ['positive']],
['rankle', ['negative']],
['attacking', ['bb']],
['buying', ['gg', 'r']],
['charging', ['r', 'bb']],
['claiming that they credited', ['gg', 'r']],
['criticising', ['bb']],
['criticizing', ['bb']],
['off better if you use', ['gn']],
['paying', ['r']],
['treat', ['positive', 'gg', 'gb']],
['treating', ['positive', 'gg', 'gb']],
['reassures', ['positive']],
['rebuffed', ['negative']],
['rebuffs', ['negative']],
['rebuke', ['negative']],
['rebuked', ['negative']],
['recommend', ['positive']],
['recommending', ['positive']],
['redeemed', ['positive']],
['refunded', ['r']],
['refuse', ['negative']],
['refused', ['negative']],
['refuses', ['negative']],
['refusing', ['negative']],
['regret', ['negative']],
['reimbursed', ['gg', 'r', 'gb']],
['reject', ['negative']],
['rejected', ['negative']],
['rejecting', ['negative']],
['rejects', ['negative']],
['rejoice', ['positive']],
['rejoicing', ['positive']],
['relax', ['positive']],
['relaxed', ['positive']],
['relieving', ['positive']],
['reminds', ['gg', 'gb']],
['repay', ['positive', 'bg']],
['repent', ['positive']],
['reprimanded', ['negative']],
['reprimands', ['negative']],
['reproach', ['negative']],
['reproached', ['negative']],
['reproaches', ['negative']],
['reprove', ['negative']],
['reproved', ['negative']],
['repulse', ['negative']],
['repulsed', ['negative']],
['rescue', ['positive']],
['rescued', ['positive']],
['rescues', ['positive']],
['rescuing', ['positive']],
['resent', ['negative', 'bb']],
['resented', ['negative']],
['resenting', ['negative', 'bg', 'bb']],
['resents', ['negative', 'bg', 'bb']],
['respect', ['positive', 'gg', 'bg']],
['respected', ['positive']],
['respecting', ['positive']],
['respects', ['positive']],
['restore', ['positive']],
['restored', ['positive']],
['retaliate', ['negative']],
['reuniting', ['positive']],
['reverted', ['negative']],
['revile', ['negative']],
['reviles', ['negative']],
['reward', ['positive', 'gg']],
['rewarded', ['positive', 'gg']],
['rewarding', ['positive']],
['rewards', ['positive']],
['ridiculed', ['negative']],
['ridicules', ['negative']],
['ruin', ['negative']],
['ruined', ['negative']],
['abandoned', ['bn', 'gb', 'bg', 'bb']],
['accepting', ['gn', 'gg', 'gb']],
['accusing', ['bb']],
['against', ['bb']],
['arresting', ['bg', 'bg', 'bb', 'bb']],
['asking', ['gg', 'gb']],
['avoiding', ['bb']],
['been pestering', ['bn', 'bb']],
['berating', ['bb']],
['blaming', ['bb']],
['burning', ['bb']],
['calling', ['positive', 'negative', 'neutral', 'gg', 'nb', 'ng', 'bb']],
['challenging', ['bb']],
['charged', ['r']],
['charging', ['r', 'bb']],
['criticizing', ['bb']],
['crushing', ['bb']],
['dumped', ['bb']],
['exposing', ['gb', 'bb']],
['fighting', ['bb']],
['forgiven', ['gb']],
['given', ['gg', 'gn', 'bn', 'gb', 'bb']],
['giving', ['gg', 'r', 'gb', 'bb', 'gn', 'bn']],
['got', ['gg', 'gb', 'gb', 'bb']],
['had', ['gg', 'gn', 'gb']],
['hating', ['bb']],
['having trouble seeing', ['gg', 'bb']],
['hired', ['gg', 'gn', 'gb']],
['ignored', ['bb']],
['killing', ['bb']],
['knocking', ['bb']],
['known', ['nb', 'ng', 'nn']],
['leaving', ['bg', 'bb']],
['left', ['bn', 'bg', 'bb']],
['liked', ['gg']],
['loving', ['gg']],
['managed to forgive', ['positive', 'gb']],
['milking', ['bg', 'bn']],
['out there somewhere thanking', ['gg']],
['paying', ['r']],
['pillorying', ['bb']],
['prepared', ['gg', 'gn', 'gb']],
['preparing', ['gg', 'gb', 'gn']],
['prepping', ['gg', 'gn', 'gb']],
['priced', ['gg']],
['proud of', ['gg']],
['punishing', ['bb']],
['recruit', ['positive', 'gg', 'gn', 'gb']],
['recruits', ['positive', 'gg', 'gn', 'gb']],
['recruited', ['positive', 'gg', 'gn', 'gb']],
['recruiting', ['positive', 'gg', 'gn', 'gb']],
['repaying', ['r']],
['resenting', ['bg', 'bb']],
['rewarded', ['gg']],
['seeing', ['gg', 'gb', 'bb']],
['seen', ['gg', 'gb', 'bb']],
['selling', ['gg', 'r']],
['sent', ['gg', 'gb']],
['still haunting', ['bb']],
['still thanking', ['gg']],
['suing', ['bb']],
['taunted', ['bg', 'bn']],
['taunting', ['bb']],
['thanked', ['gg']],
['thanking', ['gg', 'gb']],
['treated', ['gb']],
['used', ['bn', 'ng']],
['using', ['bn', 'ng']],
['volunteered', ['gg']],
['with', ['gg', 'gb']],
['sassed', ['negative']],
['sasses', ['negative']],
['satisfied', ['positive']],
['satisfies', ['positive']],
['scare', ['negative']],
['scared', ['negative']],
['scares', ['negative']],
['scaring', ['negative']],
['schedule', ['gg', 'gb']],
['scold', ['negative', 'gb']],
['scolded', ['negative']],
['scolding', ['negative']],
['scolds', ['negative']],
['scorn', ['negative']],
['scorned', ['negative']],
['scorns', ['negative']],
['scream', ['negative']],
['screamed', ['negative']],
['screw', ['negative']],
['screwed', ['negative']],
['scrutinize', ['neutral']],
['sense', ['positive']],
['senses', ['positive']],
['sent', ['gg', 'gb']],
['shadow', ['negative']],
['shake', ['negative']],
['shames', ['negative']],
['shaming', ['negative']],
['shelter', ['positive']],
['shielding', ['positive']],
['shock', ['negative']],
['shook', ['negative']],
['shun', ['negative']],
['shunned', ['negative']],
['shuns', ['negative']],
['sicken', ['negative']],
['sickened', ['negative']],
['slandered', ['negative']],
['slap', ['negative']],
['slapped', ['negative']],
['slapping', ['negative']],
['slaps', ['negative']],
['slight', ['negative']],
['slighted', ['negative']],
['smash', ['negative']],
['smear', ['negative']],
['smile', ['positive']],
['smiled', ['positive']],
['smiles', ['positive']],
['sneak', ['negative']],
['sneered', ['negative']],
['snub', ['negative']],
['snubbed', ['negative']],
['snubs', ['negative']],
['soothe', ['positive']],
['spank', ['negative']],
['spanking', ['negative']],
['spanks', ['negative']],
['spared', ['positive']],
['spares', ['positive']],
['sparing', ['positive']],
['spoil', ['negative']],
['spoiled', ['negative']],
['spoiling', ['negative']],
['spurn', ['negative']],
['spurned', ['negative']],
['spurns', ['negative']],
['squash', ['negative']],
['squashed', ['negative']],
['stab', ['negative']],
['stabbed', ['negative']],
['stabilize', ['positive']],
['stabs', ['negative']],
['startle', ['negative']],
['startled', ['negative']],
['startles', ['negative']],
['starved', ['negative']],
['starving', ['negative']],
['steal', ['negative']],
['stigmatizing', ['negative']],
['stimulate', ['positive']],
['sting', ['negative']],
['stings', ['negative']],
['stink', ['negative']],
['stirs', ['neutral']],
['stole', ['negative']],
['stumping', ['negative']],
['stun', ['negative']],
['stung', ['negative']],
['stunned', ['negative']],
['sue', ['negative', 'bb']],
['sues', ['negative', 'bb']],
['sued', ['negative', 'bb']],
['suing', ['negative', 'bb']],
['suffer', ['negative', 'bg', 'bb']],
['suffers', ['negative', 'bg', 'bb']],
['suffered', ['negative', 'bg', 'bb']],
['suffering', ['negative', 'bg', 'bb']],
['suit', ['positive']],
['suits', ['positive', 'gg']],
['surprise', ['neutral']],
['surprised', ['neutral']],
['surprises', ['neutral']],
['surprising', ['neutral']],
['swear', ['negative']],
['swindled', ['negative']],
['swore', ['negative']],
['taunt', ['negative']],
['taunted', ['negative', 'bg', 'bn']],
['taunts', ['negative']],
['terrorize', ['negative']],
['terrorizes', ['negative']],
['thank', ['positive', 'gg']],
['thanked', ['positive', 'gg']],
['thanking', ['positive', 'gg']],
['thanks', ['positive']],
['think', ['neutral']],
['thinks', ['neutral']],
['thought', ['neutral']],
['thrashed', ['negative']],
['threaten', ['negative']],
['threatened', ['negative']],
['threatening', ['negative']],
['threatens', ['negative']],
['threw', ['negative']],
['thrill', ['positive']],
['thrills', ['positive']],
['throw', ['negative']],
['throws', ['negative']],
['tickle', ['positive']],
['tickled', ['positive']],
['tickles', ['positive']],
['tolerate', ['positive']],
['tolerated', ['positive']],
['tolerates', ['positive']],
['torment', ['negative']],
['tormented', ['negative']],
['tormenting', ['negative']],
['torments', ['negative']],
['torture', ['negative']],
['tortured', ['negative']],
['torturing', ['negative']],
['train', ['gg', 'gn', 'gb']],
['treasured', ['positive']],
['treating', ['positive', 'gg', 'gb']],
['tried', ['negative']],
['trouble', ['negative']],
['trust', ['positive']],
['trusted', ['positive']],
['trustes', ['positive']],
['trusting', ['positive']],
['trusts', ['positive']],
['try', ['negative']],
['underestimate', ['negative']],
['underestimated', ['negative']],
['undermining', ['negative']],
['understand', ['positive']],
['understanding', ['positive']],
['understands', ['positive']],
['understood', ['positive']],
['unnerve', ['negative']],
['unnerves', ['negative']],
['upbraided', ['negative']],
['uplift', ['positive']],
['uplifting', ['positive']],
['uplifts', ['positive']],
['upset', ['negative']],
['upsets', ['negative']],
['upsetting', ['negative']],
['value', ['positive']],
['valued', ['positive']],
['vanished', ['negative']],
['ve asked', ['gg', 'gb']],
['ve charged', ['r', 'bb']],
['ve known', ['gg', 'nb', 'ng', 'bb']],
['ve loved', ['gg']],
['ve reimbursed', ['gg', 'r', 'gb']],
['ve signed', ['gg']],
['ve warned', ['bb']],
['venerate', ['positive']],
['vexed', ['negative']],
['vexes', ['negative']],
['vilify', ['negative']],
['vindicate', ['positive']],
['vindicated', ['positive']],
['wailed', ['negative']],
['want', ['positive', 'gg', 'gb', 'bb']],
['wanted', ['positive']],
['wants', ['positive']],
['warn', ['gb']],
['warned', ['bb']],
['weeped', ['negative']],
['welcome', ['positive']],
['welcomed', ['positive']],
['welcomes', ['positive']],
['welcoming', ['positive']],
['wish', ['positive']],
['wished', ['positive']],
['wishing', ['positive']],
['worried', ['negative']],
['worries', ['negative']],
['worry', ['negative']],
['worship', ['positive']],
['worshiped', ['positive']],
['worshipped', ['positive']],
['worships', ['positive']],
['wounds', ['negative']],
['wrestle', ['negative']],
['writhed', ['negative']],
['yearn', ['positive']],
['yearns', ['positive']],
['~abandon', ['positive', 'neutral']],
['~abuse', ['positive', 'neutral', 'bg']],
['~acknowledged', ['negative', 'neutral', 'gg', 'gb', 'gn']],
['~affect', ['neutral']],
['~answered', ['gg', 'gn', 'gb']],
['~ask', ['gg', 'gb']],
['~asked', ['gg', 'gb']],
['~believe', ['neutral', 'gg', 'gb']],
['~blame', ['positive', 'neutral', 'gb']],
['~blamed', ['positive', 'neutral', 'bb']],
['~bother', ['positive', 'neutral']],
['~charge', ['r', 'gb', 'bb', 'bg', 'r']],
['~conquer', ['negative', 'neutral']],
['~contacted', ['nb', 'ng', 'nn']],
['~cooperate', ['negative', 'neutral']],
['~deceived', ['positive', 'neutral']],
['~destroy', ['positive', 'neutral', 'bb']],
['~disappoints', ['positive', 'neutral']],
['~disrespected', ['positive', 'neutral']],
['~disturb', ['positive', 'neutral']],
['~dominate', ['positive', 'neutral']],
['~eradicate', ['positive', 'neutral']],
['~fail', ['positive', 'neutral', 'bg']],
['~fear', ['positive', 'neutral', 'bb']],
['~feed', ['gg', 'gb']],
['~fine', ['positive', 'neutral', 'bb']],
['~forgave', ['negative', 'neutral', 'gb']],
['~forget', ['positive', 'neutral']],
['~forgive', ['negative', 'neutral', 'bb']],
['~forgives', ['negative', 'neutral', 'gb']],
['~forgot', ['positive', 'neutral']],
['~foul', ['positive', 'neutral']],
['~give', ['bg', 'bb', 'bn', 'gg', 'gb', 'gb', 'gn']],
['~hate', ['positive', 'neutral', 'bb', 'bg']],
['~hear', ['gg', 'gb', 'gb', 'gn']],
['~heard', ['gg', 'gn', 'gb']],
['~hire', ['gg', 'gn', 'gb']],
['~hurt', ['positive', 'neutral', 'bb']],
['~ignore', ['positive', 'neutral']],
['~judge', ['bg', 'bn']],
['~kill', ['positive', 'neutral', 'bb']],
['~knew', ['neutral', 'gg', 'nb', 'ng', 'bb']],
['~know', ['neutral', 'gg', 'bb', 'nb', 'ng']],
['~love', ['negative', 'neutral', 'gg']],
['~loved', ['negative', 'neutral', 'gg']],
['~loves', ['negative', 'neutral']],
['~marry', ['bb']],
['~need', ['neutral']],
['~oppose', ['positive', 'neutral']],
['~pay', ['negative', 'bg', 'bb']],
['~regard', ['neutral']],
['~repay', ['negative', 'neutral', 'bg']],
['~resent', ['positive', 'neutral', 'bb']],
['~respect', ['negative', 'neutral', 'gg', 'bg']],
['~startled', ['positive', 'neutral']],
['~thanked', ['negative', 'neutral', 'gg']],
['~threaten', ['positive', 'neutral']],
['~understand', ['negative', 'neutral']],
['~want', ['negative', 'neutral', 'gg', 'gb', 'bb']],
[''],
[''],
['sold', ['gg', 'bb']],
['aid', ['gg', 'gb', 'gn']],
['aiding', ['gg', 'gb', 'gn']],
['aided', ['gg', 'gb', 'gn']],
['saves', ['gg', 'gb', 'gn']],
['#knelt', ['?']],
['sleep', ['gg', 'gn']],
['cuckolding', ['bg', 'bn']],
['mentored', ['gg', 'gb', 'gn']],
['support', ['positive', 'gg', 'gb']],
['supports', ['positive', 'gg', 'gb']],
['supported', ['positive', 'gg', 'gb']],
['supporting', ['positive', 'gg', 'gb']],
['imprison', ['gb', 'bb']],
['bully', ['bg', 'bb', 'bn']],
['press', ['bg', 'bb', 'bn']],
['pressed', ['bg', 'bb', 'bn']],
['accompany', ['gg', 'gb', 'gn']],
['accompanying', ['gg', 'gb', 'gn']],
['#achieved', ['?']],
['assault', ['negative', 'bb', 'bn']],
['assaulted', ['negative', 'bb', 'bn']],
['assaulting', ['negative', 'bb', 'bn']],
['assaults', ['negative', 'bb', 'bn']],
['beckons', ['bg', 'bn']],
['bite', ['bg', 'bb', 'bb']],
['achieved', ['gg']],
['adapted', ['gg', 'gb', 'gn']],
['adopt', ['positive', 'gg', 'gb']],
['adopted', ['positive', 'gg', 'gb']],
['adopting', ['positive', 'gg', 'gb']],
['counteract', ['gb', 'bb']],
['decked', ['bb']],
['dodge', ['bb']],
['dodged', ['bb']],
['~survive', ['bb']],
['~stop', ['gg']],
['~see', ['bb']],
['~resist', ['gg']],
['~supported', ['bb']],
['~tell', ['neutral', 'negative', 'bb']],
['~told', ['neutral', 'negative', 'bb']],
['~proselytize', ['gb', 'gn']],
['~fuck', ['bb', 'gb']],
['~follow', ['bb']],
['~heal', ['bb']],
['~hit', ['positive', 'gg']],
['~idolise', ['negative', 'neutral', 'bb']],
['bullshit', ['negative', 'bb']],
['bullshits', ['negative', 'bb']],
['bullshitted', ['negative', 'bb']],
['bumped', ['negative', 'bb']],
['bumps', ['negative', 'bb']],
['blacklisted', ['negative', 'bb']],
['bind', ['negative', 'neutral', 'bb']],
['blinded', ['negative', 'bb']],
['pulverize', ['negative', 'bb']],
['punish', ['bb']],
['punished', ['bb']],
['punishes', ['bb']],
['punishing', ['bb']],
['pursue', ['bg', 'bb', 'bn']],
['pursued', ['bg', 'bb', 'bn']],
['pursues', ['bg', 'bb', 'bn']],
['query', ['bg', 'bb', 'bn', 'ng']],
['querying', ['bg', 'bb', 'bn', 'ng']],
['question', ['negative', 'bg', 'bb', 'bn']],
['questioned', ['negative', 'bg', 'bb', 'bn']],
['questioning', ['negative', 'bg', 'bb', 'bn']],
['quiz', ['bg', 'bb', 'bn']],
['quizzed', ['bg', 'bb', 'bn']],
['quizzes', ['bg', 'bb', 'bn']],
['rammed', ['negative', 'bb']],
['rape', ['negative', 'bb', 'bn']],
['raped', ['negative', 'bb', 'bn']],
['rapes', ['negative', 'bb', 'bn']],
['raping', ['negative', 'bb', 'bn']],
['apologized', ['gb']],
['apologizes', ['gb']],
['appoint', ['positive', 'gg']],
['apprehend', ['bb']],
['apprehended', ['bb']],
['argue', ['negative', 'bb']],
['argued', ['negative', 'bb']],
['assist', ['positive', 'gg', 'gb', 'gn']],
['assisted', ['positive', 'gg', 'gb', 'gn']],
['assisting', ['positive', 'gg', 'gb', 'gn']],
['assume', ['negative', 'neutral', 'bb', 'ng', 'nb', 'nn']],
['attacked', ['negative', 'bb']],
['audit', ['negative', 'bb']],
['auditioned', ['positive', 'gg']],
['babies', ['negative', 'bb']],
['babysits', ['positive', 'gg']],
['babysitting', ['positive', 'gg']],
['backstab', ['negative', 'bb']],
['bandaging', ['positive', 'gb']],
['barked', ['negative', 'bb']],
['barks', ['negative', 'bb']],
['beating', ['negative', 'bb']],
['beats', ['negative', 'bb']],
['befooled', ['negative', 'bb']],
['belong', ['positive', 'gg', 'gn']],
['belonged', ['positive', 'gg', 'gn']],
['belongs', ['positive', 'gg', 'gn']],
['benefit', ['positive', 'gg']],
['benefits', ['positive', 'gg']],
['bit', ['negative', 'bb']],
['antagonise', ['negative', 'bb']],
['jab', ['negative', 'bb']],
['jabs', ['negative', 'bb']],
['banged', ['negative', 'bb']],
['bangs', ['negative', 'bb']],
['banned', ['bb']],
['choosing', ['gg', 'bb']],
['choosen', ['gg', 'bb']],
['circle', ['bb']],
['circles', ['bb']],
['cite', ['gg', 'bb', 'gn']],
['consult', ['gg', 'gb', 'gn']],
['consulted', ['gg', 'gb', 'gn']],
['create', ['bb', 'gg', 'gb', 'gn']],
['creating', ['bb', 'gg', 'gb', 'gn']],
['liked', ['positive', 'gg']],
['miss', ['negative', 'bb']],
['missed', ['negative', 'bb']],
['tell', ['positive', 'gg', 'gb', 'gn']],
['tells', ['positive', 'gg', 'gb', 'gn']],
['do', ['gg', 'gb', 'gn']],
['did', ['gg', 'gb', 'gn']],
['does', ['gg', 'gb', 'gn']],
['likes', ['positive', 'gg', 'gn', 'gb']],
['follow', ['positive', 'gg']],
['teach', ['positive', 'gg', 'gb', 'gn']],
['teaches', ['positive', 'gg', 'gb', 'gn']],
['taught', ['positive', 'gg', 'gb', 'gn']],
['teaching', ['positive', 'gg', 'gb', 'gn']],
['told', ['gg', 'gb', 'gn']],
['see', ['neutral', 'gg', 'bb']],
['saw', ['neutral', 'gg', 'bb']],
['come', ['positive', 'neutral', 'gg', 'gb']],
['comes', ['positive', 'neutral', 'gg', 'gb']],
['came', ['positive', 'neutral', 'gg', 'gb']],
['~outlast', ['negative', 'bb']],
['remember', ['positive', 'neutral', 'gg', 'bb']],
['remembers', ['positive', 'neutral', 'gg', 'bb']],
['remembered', ['positive', 'neutral', 'gg', 'bb']],
['remembering', ['positive', 'neutral', 'gg', 'bb']],
['shot', ['negative', 'bb']],
['touch', ['positive', 'neutral', 'negative', 'gg', 'bb', 'bn']],
['touched', ['positive', 'neutral', 'negative', 'gg', 'bb', 'bn']],
['saved', ['positive', 'gg', 'gb', 'gn']],
['use', ['neutral', 'negative', 'gg', 'gb', 'gn', 'bg', 'bn']],
['used', ['neutral', 'negative', 'gg', 'gb', 'gn', 'bg', 'bn']],
['misses', ['negative', 'bb']],
['learn', ['positive', 'gg', 'gb', 'gn']],
['learned', ['positive', 'gg', 'gb', 'gn']],
['learnt', ['positive', 'gg', 'gb', 'gn']],
['watch', ['positive', 'neutral', 'gg', 'bb']],
['watches', ['positive', 'neutral', 'gg', 'bb']],
['watched', ['positive', 'neutral', 'gg', 'bb']],
['watching', ['positive', 'neutral', 'gg', 'bb']],
['said', ['positive', 'negative', 'neutral', 'gg', 'nb', 'ng', 'bb']],
['abides', ['positive', 'gg', 'gb', 'gn']],
['work', ['positive', 'neutral', 'gg', 'gn']],
['push', ['positive', 'negative', 'bb']],
['pushes', ['positive', 'negative', 'bb']],
['pushed', ['positive', 'negative', 'bb']],
['pushing', ['positive', 'negative', 'bb']],
['talk', ['positive', 'neutral', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['talks', ['positive', 'neutral', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['talked', ['positive', 'neutral', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['talking', ['positive', 'neutral', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['let', ['positive', 'neutral', 'gg', 'gb', 'gn']],
['meet', ['positive', 'gg', 'gb']],
['met', ['positive', 'gg', 'gb']],
['sued', ['negative', 'bb']],
['kicked', ['negative', 'bb']],
['supported', ['positive', 'gg']],
['chased', ['negative', 'bb']],
['sees', ['gg', 'gb', 'bb']],
['shoot', ['negative', 'bb']],
['shoots', ['negative', 'bb']],
['shot', ['negative', 'bb']],
['shooting', ['negative', 'bb']],
['interview', ['positive', 'neutral', 'gg', 'gb', 'gn', 'nb', 'ng', 'bb']],
['slew', ['negative', 'bb']],
['fight', ['negative', 'bb']],
['bruise', ['negative', 'bb']],
['visit', ['positive', 'gg']],
['visited', ['positive', 'gg']],
['met', ['neutral', 'gg', 'bb']],
['made', ['positive', 'gg', 'gn']],
['pushed', ['positive', 'negative', 'gg', 'gb', 'gn', 'bb', 'bn']],
['remember', ['positive', 'negative', 'gg', 'bb']],
['am', ['neutral']],
['is', ['neutral']],
['are', ['neutral']],
['was', ['neutral']],
['be', ['positive', 'negative', 'neutral', 'gg', 'gn']],
['made', ['positive', 'gg', 'gn']],
['touch', ['positive', 'neutral', 'negative', 'gg', 'bb']],
['depend', ['bg', 'bb', 'bn']],
['email', ['positive', 'negative', 'neutral', 'bb', 'nb', 'ng', 'gg']],
['emails', ['positive', 'negative', 'neutral', 'bb', 'nb', 'ng', 'gg']],
['emailed', ['positive', 'negative', 'neutral', 'bb', 'nb', 'ng', 'gg']],
['emailing', ['positive', 'negative', 'neutral', 'bb', 'nb', 'ng', 'gg']],
['punched', ['negative', 'bb']],
['speak', ['positive', 'neutral', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['spoke', ['positive', 'neutral', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['cheated', ['negative', 'bb']],
['leave', ['negative', 'bb']],
['shoved', ['negative', 'bb']],
['hug', ['positive', 'gg']],
['recognize', ['positive', 'negative', 'neutral', 'gg', 'gb', 'bb']],
['recognized', ['positive', 'negative', 'neutral', 'gg', 'gb', 'bb']],
['texted', ['bb', 'nb', 'ng', 'gg']],
['educate', ['positive', 'gg', 'gb', 'gn']],
['educates', ['positive', 'gg', 'gn', 'gb']],
['educated', ['positive', 'gg', 'gn', 'gb']],
['seek', ['positive', 'negative', 'gg', 'bb']],
['seeks', ['positive', 'negative', 'gg', 'bb']],
['sought', ['positive', 'negative', 'gg', 'bb']],
['seeking', ['positive', 'negative', 'gg', 'bb']],
['honours', ['positive', 'gg']],
['represent', ['positive', 'neutral', 'gg', 'gb', 'gn']],
['listen', ['gg', 'gb', 'gn']],
['go', ['neutral', 'positive', 'gg', 'gb', 'gn']],
['goes', ['neutral', 'positive', 'gg', 'gb', 'gn']],
['went', ['neutral', 'positive', 'gg', 'gb', 'gn']],
['going', ['neutral', 'positive', 'gg', 'gb', 'gn']],
['turned', ['neutral', 'positive', 'negative', 'gb', 'bb']],
['serve', ['positive', 'gg', 'bb', 'gn']],
['serves', ['positive', 'gg', 'bb', 'gn']],
['served', ['positive', 'gg', 'bb', 'gn']],
['serving', ['positive', 'gg', 'bb', 'gn']],
['reach', ['positive', 'negative', 'gg', 'bb', 'ng', 'nb']],
['reaches', ['positive', 'negative', 'gg', 'bb', 'ng', 'nb']],
['reached', ['positive', 'negative', 'gg', 'bb', 'ng', 'nb']],
['reaching', ['positive', 'negative', 'gg', 'bb', 'ng', 'nb']],
['boo', ['negative', 'bb']],
['boos', ['negative', 'bb']],
['booed', ['negative', 'bb']],
['booing', ['negative', 'bb']],
['divorced', ['negative', 'bb']],
['tease', ['negative', 'bb']],
['teases', ['negative', 'bb']],
['teased', ['negative', 'bb']],
['teasing', ['negative', 'bb']],
['trapped', ['negative', 'bb']],
['downvoted', ['negative', 'bb']],
['jump', ['negative', 'bb']],
['digs', ['positive', 'gg']],
['scarred', ['negative', 'bb']],
['slept', ['positive', 'gg']],
['desert', ['negative', 'bb']],
['wink', ['positive', 'gg']],
['baptised', ['positive', 'gg']],
['dwell', ['negative', 'bg', 'bb']],
['tackles', ['negative', 'bb']],
['smacking', ['negative', 'bb']],
['stereotype', ['negative', 'bn']],
['hears', ['positive', 'neutral', 'gg', 'gb', 'gn']],
['own', ['negative', 'bb', 'bn']],
['fuck', ['negative', 'bb']],
['fucks', ['negative', 'bb']],
['fucked', ['negative', 'bb']],
['play', ['positive', 'gg', 'bb']],
['plays', ['positive', 'gg', 'bb']],
['played', ['positive', 'gg', 'bb']],
['playing', ['positive', 'gg', 'bb']],
['walk', ['positive', 'neutral', 'gg', 'gb', 'gn']],
['stayed', ['positive', 'gg', 'gb']],
['influence', ['negative', 'bg', 'bb']],
['influences', ['negative', 'bg', 'bb']],
['influenced', ['negative', 'bg', 'bb']],
['influencing', ['negative', 'bg', 'bb']],
['rag', ['negative', 'bb']],
['lived', ['positive', 'neutral', 'gg', 'bb']],
['forbade', ['negative', 'bb']],
['chases', ['negative', 'bb']],
['lie', ['negative', 'bb']],
['lies', ['negative', 'bb']],
['lied', ['negative', 'bb']],
['lying', ['negative', 'bb']],
['inform', ['positive', 'gg', 'gb', 'gn']],
['shelled', ['negative', 'bb']],
['yell', ['negative', 'neutral', 'bb', 'ng', 'nb']],
['yells', ['negative', 'neutral', 'bb', 'ng', 'nb']],
['yelled', ['negative', 'neutral', 'bb', 'ng', 'nb']],
['yelling', ['negative', 'neutral', 'bb', 'ng', 'nb']],
['shout', ['negative', 'neutral', 'bb', 'ng', 'nb']],
['shouts', ['negative', 'neutral', 'bb', 'ng', 'nb']],
['shouted', ['negative', 'neutral', 'bb', 'ng', 'nb']],
['shouting', ['negative', 'neutral', 'bb', 'ng', 'nb']],
['rely', ['negative', 'bg', 'bg']],
['relies', ['negative', 'bg', 'bg']],
['relied', ['negative', 'bg', 'bg']],
['relying', ['negative', 'bg', 'bg']],
['depend', ['negative', 'bg', 'bg']],
['depends', ['negative', 'bg', 'bg']],
['depended', ['negative', 'bg', 'bg']],
['depending', ['negative', 'bg', 'bg']],
['fancies', ['positive', 'gg']],
['rocked', ['positive', 'negative', 'gb', 'bb']],
['humbugged', ['negative', 'bb']],
['indulged', ['negative', 'bg']],
['cheat', ['negative', 'bb']],
['trick', ['negative', 'bb']],
['tricks', ['negative', 'bb']],
['tricked', ['negative', 'bb']],
['tricking', ['negative', 'bb']],
['nailed', ['negative', 'bb']],
['domesticated', ['negative', 'neutral', 'bg', 'bb', 'bn']],
['suffocated', ['negative', 'bb']],
['wronged', ['negative', 'bb']],
['promised', ['positive', 'gg', 'gb']],
['scam', ['negative', 'bb']],
['strangled', ['negative', 'bb']],
['jumps', ['negative', 'bb']],
['rob', ['negative', 'bb']],
['fellowed', ['positive', 'gg']],
['sponsor', ['positive', 'gg']],
['strengthened', ['positive', 'gg']],
['terrify', ['negative', 'bb']],
['terrifies', ['negative', 'bb']],
['terrified', ['negative', 'bb']],
['terrifying', ['negative', 'bb']],
['nurse', ['positive', 'gg']],
['flashed', ['negative', 'bb']],
['stop', ['negative', 'bb']],
['stops', ['negative', 'bb']],
['stopped', ['negative', 'bb']],
['stopping', ['negative', 'bb']],
['mistreats', ['negative', 'bb']],
['resist', ['negative', 'bb']],
['resists', ['negative', 'bb']],
['resisted', ['negative', 'bb']],
['resisting', ['negative', 'bb']],
['humanize', ['positive', 'gg']],
['command', ['negative', 'neutral', 'ng', 'bb']],
['commands', ['negative', 'neutral', 'ng', 'bb']],
['commanded', ['negative', 'neutral', 'ng', 'bb']],
['commanding', ['negative', 'neutral', 'ng', 'bb']],
['invest', ['positive', 'gg']],
['advises', ['positive', 'gg']],
['selected', ['positive', 'gg']],
['slam', ['negative', 'bb']],
['heal', ['positive', 'gb']],
['heals', ['positive', 'gb']],
['healed', ['positive', 'gb']],
['healing', ['positive', 'gb']],
['study', ['positive', 'neutral', 'gg', 'bb']],
['studies', ['positive', 'neutral', 'gg', 'bb']],
['studied', ['positive', 'neutral', 'gg', 'bb']],
['studying', ['positive', 'neutral', 'gg', 'bb']],
['ticket', ['negative', 'bb']],
['tickets', ['negative', 'bb']],
['ticketed', ['negative', 'bb']],
['ticketing', ['negative', 'bb']],
['oblige', ['positive', 'gg']],
['obliges', ['positive', 'gg']],
['obliged', ['positive', 'gg']],
['obliging', ['positive', 'gg']],
['subsidize', ['positive', 'gg', 'gb']],
['subsidizes', ['positive', 'gg', 'gb']],
['subsidized', ['positive', 'gg', 'gb']],
['subsidizing', ['positive', 'gg', 'gb']],
['flatten', ['negative', 'bb']],
['flattens', ['negative', 'bb']],
['flattened', ['negative', 'bb']],
['flattening', ['negative', 'bb']],
['outnumber', ['negative']],
['~hide', ['positive', 'gg', 'gb']],
['disinherit', ['negative', 'bb']],
['disinherits', ['negative', 'bb']],
['disinherited', ['negative', 'bb']],
['disinheriting', ['negative', 'bb']],
['request', ['positive', 'negative', 'neutral', 'gg', 'gb', 'bg', 'bb', 'ng', 'nb']],
['requests', ['positive', 'negative', 'neutral', 'gg', 'gb', 'bg', 'bb', 'ng', 'nb']],
['requested', ['positive', 'negative', 'neutral', 'gg', 'gb', 'bg', 'bb', 'ng', 'nb']],
['requesting', ['positive', 'negative', 'neutral', 'gg', 'gb', 'bg', 'bb', 'ng', 'nb']],
['fool', ['negative', 'bb']],
['fools', ['negative', 'bb']],
['fooled', ['negative', 'bb']],
['fooling', ['negative', 'bb']],
['manufacture', ['positive', 'neutral', 'gg', 'gb', 'gn']],
['~beat', ['positive', 'negative', 'gg', 'bb']],
['~call', ['negative', 'bb']],
['champion', ['positive', 'gg', 'gb']],
['champions', ['positive', 'gg', 'gb']],
['championed', ['positive', 'gg', 'gb']],
['championing', ['positive', 'gg', 'gb']],
['gain', ['positive', 'gg']],
['gains', ['positive', 'gg']],
['gained', ['positive', 'gg']],
['gaining', ['positive', 'gg']],
['swarm', ['negative', 'bb']],
['swarms', ['negative', 'bb']],
['swarmed', ['negative', 'bb']],
['swarming', ['negative', 'bb']],
['withdraw', ['negative', 'bb']],
['withdraws', ['negative', 'bb']],
['withdrew', ['negative', 'bb']],
['withdrawing', ['negative', 'bb']],
['rip', ['negative', 'bb']],
['rips', ['negative', 'bb']],
['ripped', ['negative', 'bb']],
['ripping', ['negative', 'bb']],
['escape', ['positive', 'gb']],
['escapes', ['positive', 'gb']],
['escaped', ['positive', 'gb']],
['escaping', ['positive', 'gb']],
['squeeze', ['negative', 'bb']],
['squeezes', ['negative', 'bb']],
['squeezed', ['negative', 'bb']],
['squeezing', ['negative', 'bb']],
['correct', ['positive', 'negative', 'gb']],
['corrects', ['positive', 'negative', 'gb']],
['corrected', ['positive', 'negative', 'gb']],
['correcting', ['positive', 'negative', 'gb']],
['~invade', ['positive', 'gg', 'gb']],
['infect', ['negative', 'bb']],
['spit', ['negative', 'bb']],
['spitted', ['negative', 'bb']],
['spat', ['negative', 'bb']],
['spitting', ['negative', 'bb']],
['butcher', ['negative', 'bb']],
['butchers', ['negative', 'bb']],
['butchered', ['negative', 'bb']],
['butchering', ['negative', 'bb']],
['nudge', ['positive', 'gg', 'gb']],
['nudges', ['positive', 'gg', 'gb']],
['nudged', ['positive', 'gg', 'gb']],
['nudging', ['positive', 'gg', 'gb']],
['whack', ['negative', 'bb']],
['whacks', ['negative', 'bb']],
['whacked', ['negative', 'bb']],
['whacking', ['negative', 'bb']],
['pressure', ['negative', 'bb']],
['pressures', ['negative', 'bb']],
['pressured', ['negative', 'bb']],
['pressuring', ['negative', 'bb']],
['invade', ['negative', 'bb']],
['invades', ['negative', 'bb']],
['invaded', ['negative', 'bb']],
['invading', ['negative', 'bb']],
['knock', ['negative', 'bb']],
['knocks', ['negative', 'bb']],
['knocked', ['negative', 'bb']],
['knocking', ['negative', 'bb']],
['commemorate', ['positive', 'gg']],
['commemorates', ['positive', 'gg']],
['commemorated', ['positive', 'gg']],
['commemorating', ['positive', 'gg']],
['dance', ['positive', 'gg']],
['dances', ['positive', 'gg']],
['danced', ['positive', 'gg']],
['dancing', ['positive', 'gg']],
['ostracise', ['negative', 'bb']],
['ostracises', ['negative', 'bb']],
['ostracised', ['negative', 'bb']],
['ostracising', ['negative', 'bb']],
['ostracize', ['negative', 'bb']],
['ostracizes', ['negative', 'bb']],
['ostracized', ['negative', 'bb']],
['ostracizing', ['negative', 'bb']],
['clap', ['positive', 'gg']],
['claps', ['positive', 'gg']],
['clapped', ['positive', 'gg']],
['clapping', ['positive', 'gg']],
['complete', ['positive', 'gg']],
['completes', ['positive', 'gg']],
['completed', ['positive', 'gg']],
['completing', ['positive', 'gg']],
['hide', ['negative', 'bb']],
['hides', ['negative', 'bb']],
['hid', ['negative', 'bb']],
['hiding', ['negative', 'bb']],
['return', ['positive', 'gg']],
['returns', ['positive', 'gg']],
['returned', ['positive', 'gg']],
['returning', ['positive', 'gg']],
['sack', ['negative', 'bb']],
['sacks', ['negative', 'bb']],
['sacked', ['negative', 'bb']],
['sacking', ['negative', 'bb']],
['drown', ['negative', 'bb']],
['drowns', ['negative', 'bb']],
['drowned', ['negative', 'bb']],
['drowning', ['negative', 'bb']],
['cane', ['negative', 'bb']],
['canes', ['negative', 'bb']],
['caned', ['negative', 'bb']],
['caning', ['negative', 'bb']],
['trash', ['negative', 'bb']],
['trashes', ['negative', 'bb']],
['trashed', ['negative', 'bb']],
['trashing', ['negative', 'bb']],
['~compromise', ['negative', 'bb']],
['~compromises', ['negative', 'bb']],
['~compromised', ['negative', 'bb']],
['~compromising', ['negative', 'bb']],
['rush', ['negative', 'bb']],
['rushes', ['negative', 'bb']],
['rushed', ['negative', 'bb']],
['rushing', ['negative', 'bb']],
['run', ['positive', 'negative', 'gg', 'bb']],
['runs', ['positive', 'negative', 'gg', 'bb']],
['ran', ['positive', 'negative', 'gg', 'bb']],
['running', ['positive', 'negative', 'gg', 'bb']],
['look', ['positive', 'negative', 'neutral', 'gg', 'bb']],
['looks', ['positive', 'negative', 'neutral', 'gg', 'bb']],
['looked', ['positive', 'negative', 'neutral', 'gg', 'bb']],
['looking', ['positive', 'negative', 'neutral', 'gg', 'bb']],
['remind', ['positive', 'negative', 'gb']],
['reminds', ['positive', 'negative', 'gb']],
['reminded', ['positive', 'negative', 'gb']],
['reminding', ['positive', 'negative', 'gb']],
['lose', ['negative', 'bb']],
['loses', ['negative', 'bb']],
['lost', ['negative', 'bb']],
['losing', ['negative', 'bb']],
['eye', ['positive', 'negative', 'bg', 'bb', 'bn']],
['eyes', ['positive', 'negative', 'bg', 'bb', 'bn']],
['eyed', ['positive', 'negative', 'bg', 'bb', 'bn']],
['eyeing', ['positive', 'negative', 'bg', 'bb', 'bn']],
['house', ['positive', 'gg', 'gb']],
['houses', ['positive', 'gg', 'gb']],
['housed', ['positive', 'gg', 'gb']],
['housing', ['positive', 'gg', 'gb']],
['scratch', ['negative', 'bb']],
['scratches', ['negative', 'bb']],
['scratched', ['negative', 'bb']],
['scratching', ['negative', 'bb']],
['ogle', ['negative', 'bb']],
['ogles', ['negative', 'bb']],
['ogled', ['negative', 'bb']],
['ogling', ['negative', 'bb']],
['outrun', ['positive', 'gb']],
['outruns', ['positive', 'gb']],
['outran', ['positive', 'gb']],
['outrunning', ['positive', 'gb']],
['flee', ['negative', 'gb', 'bb']],
['flees', ['negative', 'gb', 'bb']],
['fleed', ['negative', 'gb', 'bb']],
['fleeing', ['negative', 'gb', 'bb']],
['kick', ['negative', 'bb']],
['kicks', ['negative', 'bb']],
['kicked', ['negative', 'bb']],
['kicking', ['negative', 'bb']],
['remonstrate', ['negative', 'bb']],
['remonstrates', ['negative', 'bb']],
['remonstrated', ['negative', 'bb']],
['remonstrating', ['negative', 'bb']],
['release', ['positive', 'gg']],
['releases', ['positive', 'gg']],
['released', ['positive', 'gg']],
['releasing', ['positive', 'gg']],
['write', ['positive', 'negative', 'neutral', 'bb', 'nb', 'ng', 'gg']],
['writes', ['positive', 'negative', 'neutral', 'bb', 'nb', 'ng', 'gg']],
['wrote', ['positive', 'negative', 'neutral', 'bb', 'nb', 'ng', 'gg']],
['writing', ['positive', 'negative', 'neutral', 'bb', 'nb', 'ng', 'gg']],
['invite', ['positive', 'gg']],
['invites', ['positive', 'gg']],
['invited', ['positive', 'gg']],
['inviting', ['positive', 'gg']],
['sniff', ['negative', 'bb']],
['sniffs', ['negative', 'bb']],
['sniffed', ['negative', 'bb']],
['sniffing', ['negative', 'bb']],
['stare', ['negative', 'bb']],
['stares', ['negative', 'bb']],
['stared', ['negative', 'bb']],
['staring', ['negative', 'bb']],
['paint', ['positive', 'negative', 'gg', 'bb']],
['paints', ['positive', 'negative', 'gg', 'bb']],
['painted', ['positive', 'negative', 'gg', 'bb']],
['painting', ['positive', 'negative', 'gg', 'bb']],
['libel', ['negative', 'bb']],
['libels', ['negative', 'bb']],
['libeled', ['negative', 'bb']],
['libeling', ['negative', 'bb']],
['surround', ['negative', 'neutral', 'bb']],
['surrounds', ['negative', 'neutral', 'bb']],
['surrounded', ['negative', 'neutral', 'bb']],
['surrounding', ['negative', 'neutral', 'bb']],
['kidnap', ['negative', 'bb']],
['kidnaps', ['negative', 'bb']],
['kidnapped', ['negative', 'bb']],
['kidnapping', ['negative', 'bb']],
['whip', ['negative', 'bb']],
['whips', ['negative', 'bb']],
['whipped', ['negative', 'bb']],
['whipping', ['negative', 'bb']],
['slash', ['negative', 'bb']],
['slashes', ['negative', 'bb']],
['slashed', ['negative', 'bb']],
['slashing', ['negative', 'bb']],
['snap', ['negative', 'bb']],
['snaps', ['negative', 'bb']],
['snapped', ['negative', 'bb']],
['snapping', ['negative', 'bb']],
['receive', ['positive', 'gg']],
['receives', ['positive', 'gg']],
['received', ['positive', 'gg']],
['receiving', ['positive', 'gg']],
['control', ['negative', 'bb']],
['controls', ['negative', 'bb']],
['controlled', ['negative', 'bb']],
['controlling', ['negative', 'bb']],
['rebel', ['negative', 'bb']],
['rebels', ['negative', 'bb']],
['rebelled', ['negative', 'bb']],
['rebelling', ['negative', 'bb']],
['contact', ['positive', 'neutral', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['contacts', ['positive', 'neutral', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['contacted', ['positive', 'neutral', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['contacting', ['positive', 'neutral', 'bg', 'bb', 'bb', 'bn', 'nb', 'gg', 'ng']],
['sing', ['positive', 'gg', 'gb']],
['sings', ['positive', 'gg', 'gb']],
['sang', ['positive', 'gg', 'gb']],
['singing', ['positive', 'gg', 'gb']],
['~control', ['positive', 'gg', 'gb']],
['~controls', ['positive', 'gg', 'gb']],
['~controlled', ['positive', 'gg', 'gb']],
['~controlling', ['positive', 'gg', 'gb']],
['fulfill', ['positive', 'gg']],
['fulfills', ['positive', 'gg']],
['fulfilled', ['positive', 'gg']],
['fulfilling', ['positive', 'gg']],
['delight', ['positive', 'gg']],
['delights', ['positive', 'gg']],
['delighted', ['positive', 'gg']],
['delighting', ['positive', 'gg']],
['ride', ['negative', 'bb']],
['rides', ['negative', 'bb']],
['rode', ['negative', 'bb']],
['riding', ['negative', 'bb']],
['finger', ['positive', 'negative', 'gg', 'bb']],
['fingers', ['positive', 'negative', 'gg', 'bb']],
['fingered', ['positive', 'negative', 'gg', 'bb']],
['fingering', ['positive', 'negative', 'gg', 'bb']],
['wait', ['negative', 'neutral', 'bg', 'bb', 'bn']],
['waits', ['negative', 'neutral', 'bg', 'bb', 'bn']],
['waited', ['negative', 'neutral', 'bg', 'bb', 'bn']],
['waiting', ['negative', 'neutral', 'bg', 'bb', 'bn']],
['~answer', ['negative', 'bb']],
['~answers', ['negative', 'bb']],
['~answered', ['negative', 'bb']],
['~answering', ['negative', 'bb']],
['pay', ['positive', 'r', 'gg']],
['pays', ['positive', 'r', 'gg']],
['paid', ['positive', 'r', 'gg']],
['paying', ['positive', 'r', 'gg']],
['generalise', ['positive', '']],
['lean', ['negative', 'bg']],
['leans', ['negative', 'bg']],
['leaned', ['negative', 'bg']],
['leaning', ['negative', 'bg']],
['steer', ['positive', 'negative', 'neutral', 'nn', 'nb', 'ng']],
['steers', ['positive', 'negative', 'neutral', 'nn', 'nb', 'ng']],
['steered', ['positive', 'negative', 'neutral', 'nn', 'nb', 'ng']],
['steering', ['positive', 'negative', 'neutral', 'nn', 'nb', 'ng']],
['fill', ['positive', 'negative', 'gb', 'gg', 'bb']],
['fills', ['positive', 'negative', 'gb', 'gg', 'bb']],
['filled', ['positive', 'negative', 'gb', 'gg', 'bb']],
['filling', ['positive', 'negative', 'gb', 'gg', 'bb']]]
