// vars: vp_to_root_map, root_to_vps_map

vp_to_root_map = {'fawn': 'fawn', 'aided': 'aid', 'pardon': 'pardon', 'represent': 'represent', 'saves': 'save', 'knelt': 'kneel', 'sleep': 'sleep', 'hating': 'hate', 'hate': 'hate', 'cuckolding': 'cuckold', 'feeding': 'feed', 'granting': 'grant', 'scold': 'scold', 'tickle': 'tickle', 'ingored': 'ignore', 'caned': 'cane', 'rankle': 'rankle', 'teaching': 'teach', 'whack': 'whack', 'nourishes': 'nourish', 'shielding': 'shield', 'rescue': 'rescue', 'nourished': 'nourish', 'affect': 'affect', 'blanked': 'blank', 'bringing': 'bring', 'encounter': 'encounter', 'disturb': 'disturb', 'receiving': 'receive', 'molesting': 'molest', 'pinch': 'pinch', 'neeeds': 'need', 'honor': 'honor', 'notifying': 'notify', 'guiding': 'guide', 'shafted': 'shaft', 'enhance': 'enhance', 'disfellowshipped': 'disfellowship', 'commented': 'comment', 'enjoy': 'enjoy', 'force': 'force', 'disciplines': 'discipline', 'tolerate': 'tolerate', '~kill': '~kill', 'disciplined': 'discipline', 'scrutinize': 'scrutinize', 'complimented': 'compliment', 'sustaining': 'sustain', 'estimated': 'estimate', 'phoned': 'phone', 'humbugged': 'humbug', 'hide': 'hide', 'tiered': 'tier', 'saved': 'save', 'selected': 'select', 'liberated': 'liberate', 'abides': 'abide', 'tole': '', 'told': 'tell', 'personifies': 'personify', 'pats': 'pat', 'kicked': 'kick', 'disobeying': 'disobey', 'interrupting': 'interrupt', 'stared': 'stare', 'drew': 'draw', '~accompany': '~accompany', 'drooled': 'drool', 'reported': 'report', 'fullill': '', 'personified': 'personify', 'represented': 'represent', 'stares': 'stare', "aren't": '~be', 'interpret': 'interpret', 'uplifting': 'uplift', 'study': 'study', 'changed': 'change', 'snotted': 'snot', 'ignoring': 'ignore', 'entreating': 'entreat', 'smoke': 'smoke', 'adopting': 'adopt', 'changes': 'change', 'intrigue': 'intrigue', 'ridiculed': 'ridicule', 'resurrected': 'resurrect', 'stray': 'stray', 'explained': 'explain', 'brought': 'bring', 'shun': 'shun', 'cheats': 'cheat', 'ridicules': 'ridicule', 'drowned': 'drown', 'punching': 'punch', 'presents': 'present', 'cherishing': 'cherish', 'cheating': 'cheat', 'spoke': 'speak', 'motivate': 'motivate', 'barks': 'bark', 'chooses': 'choose', 'insult': 'insult', 'distributing': 'distribute', 'reverenced': 'reverence', 'call': 'call', 'recommend': 'recommend', 'strike': 'strike', 'mutting': '', 'tell': 'tell', 'voted': 'vote', 'suffocated': 'suffocate', 'meowed': 'meow', 'relax': 'relax', 'expose': 'expose', 'hurt': 'hurt', 'warn': 'warn', 'phone': 'phone', 'overtake': 'overtake', 'menaced': 'menace', 'rip': 'rip', 'tolerates': 'tolerate', 'robbing': 'rob', 'hold': 'hold', 'shoot': 'shoot', 'join': 'join', 'wore': 'wear', 'divorced': 'divorce', 'pursue': 'pursue', 'work': 'work', 'refusing': 'refuse', 'entertained': 'entertain', 'resents': 'resent', 'divorces': 'divorce', 'criticizing': 'criticize', 'shook': 'shake', '~impress': '~impress', 'give': 'give', 'loosed': 'loose', 'laughs': 'laugh', 'motivated': 'motivate', 'faked': 'fake', 'loaning': 'loan', 'want': 'want', 'attract': 'attract', 'cites': 'cite', 'loathe': 'loathe', 'misperceive': 'misperceive', 'scolding': 'scold', 'provide': 'provide', '~defends': '~defend', 'revisit': 'revisit', 'bandaging': 'bandage', 'cures': 'cure', 'answer': 'answer', 'disappoint': 'disappoint', 'eyeballs': 'eyeball', 'pokes': 'poke', 'replacing': 'replace', 'wrong': 'wrong', 'poked': 'poke', 'suing': 'sue', 'chined': 'chine', 'assimilates': 'assimilate', 'envy': 'envy', 'acknowledged': 'acknowledge', 'greet': 'greet', 'neglect': 'neglect', 'wink': 'wink', '~oppose': '~oppose', 'acknowledges': 'acknowledge', 'reproved': 'reprove', 'welcomed': 'welcome', '~deserve': '~deserve', 'jabs': 'jab', 'tricked': 'trick', '~distinguish': '~distinguish', 'banged': 'bang', 'rewarded': 'reward', 'patronized': 'patronize', 'stabbed': 'stab', 'clapped': 'clap', 'welcomes': 'welcome', 'fit': 'fit', 'accelerates': 'accelerate', '~change': '~change', 'writing': 'write', 'destroyed': 'destroy', 'glanced': 'glance', 'carve': 'carve', 'yells': 'yell', '~listen': '~listen', 'undercut': 'undercut', 'glorify': 'glorify', 'babies': 'baby', '~marry': '~marry', 'prevented': 'prevent', 'enrich': 'enrich', 'commemorate': 'commemorate', 'educating': 'educate', '~blamed': '~blame', '~fear': '~fear', '~resist': '~resist', 'arrested': 'arrest', 'absolve': 'absolve', 'harming': 'harm', 'dumps': 'dump', 'leaned': 'lean', 'discipline': 'discipline', 'went': 'go', 'mean': 'mean', 'lifted': 'lift', 'kneels': 'kneel', 'dumping': 'dump', 'joined': 'join', 'carry': 'carry', 'taught': 'teach', 'hosted': 'host', 'blinded': 'blind', 'depress': 'depress', 'idolised': 'idolise', 'washed': 'wash', 'encourage': 'encourage', 'banning': 'ban', 'got': 'get', 'suckleth': 'suckle', 'assaults': 'assault', 'assured': 'assure', 'threatened': 'threaten', 'free': 'free', 'smacking': 'smack', 'corrects': 'correct', 'wanted': 'want', 'zaps': 'zap', 'unequip': '', 'auditioned': 'audition', 'exposing': 'expose', 'gamahuched': '', 'reprimanded': 'reprimand', 'disturbed': 'disturb', 'oppose': 'oppose', 'competed': 'compete', 'tempting': 'tempt', 'heckle': 'heckle', 'arrived': 'arrive', 'messaged': 'message', 'bite': 'bite', 'recite': 'recite', 'enraged': 'enrage', 'rang': 'ring', 'wronged': 'wrong', 'grade': 'grade', 'encouraging': 'encourage', 'comforted': 'comfort', 'hearing': 'hear', 'hook': 'hook', 'instruct': 'instruct', '~survive': '~survive', '~asked': '~ask', 'quilt': 'quilt', 'service': 'service', 'rejects': 'reject', 'baptised': 'baptise', 'needed': 'need', '~challenge': '~challenge', 'rates': 'rate', 'listed': 'list', 'dwell': 'dwell', 'crunched': 'crunch', 'damaging': 'damage', 'listen': 'listen', 'rewards': 'reward', 'lunges': 'lunge', 'serve': 'serve', 'took': 'take', 'rejected': 'reject', 'digs': 'dig', 'chauffeuring': 'chauffeur', 'abandoning': 'abandon', 'summon': 'summon', 'target': 'target', 'showed': 'show', 'tackles': 'tackle', 'matter': 'matter', 'flame': 'flame', 'spoiled': 'spoil', 'tackled': 'tackle', 'feeling': 'feel', 'rag': 'rag', 'humble': 'humble', 'sees': 'see', 'ran': 'run', 'mind': 'mind', '~feed': '~feed', 'seen': 'see', 'seem': 'seem', 'urinate': 'urinate', 'seek': 'seek', 'tells': 'tell', 'forced': 'force', 'alkalize': 'alkalize', 'nagged': 'nag', 'overtook': 'overtake', 'instructs': 'instruct', 'laughed': 'laugh', 'grips': 'grip', 'circles': 'circle', 'starved': 'starve', 'tormenting': 'torment', 'reverence': 'reverence', 'resonated': 'resonate', '~bother': '~bother', 'repulse': 'repulse', 'assisting': 'assist', 'emailing': 'email', 'consumed': 'consume', 'flow': 'flow', 'forsook': 'forsake', 'mailing': 'mail', 'annoyed': 'annoy', 'came': 'come', 'bait': 'bait', 'inspire': 'inspire', 'contacted': 'contact', 'unhooked': 'unhook', 'seduces': 'seduce', 'nominated': 'nominate', 'disturbs': 'disturb', 'anesthetize': 'anesthetize', 'heckled': 'heckle', 'enjoyed': 'enjoy', 'touches': 'touch', 'bullshitted': 'bullshit', 'sleeps': 'sleep', 'regaled': 'regale', 'nuking': 'nuke', 'bust': 'bust', 'appreciated': 'appreciate', 'spits': 'spit', 'touched': 'touch', 'disgust': 'disgust', 'enslave': 'enslave', 'wearing': 'wear', 'do': 'do', 'godzilla': '', 'rejoicing': 'rejoice', '~forgave': '~forgive', '~ask': '~ask', 'watch': 'watch', 'denounce': 'denounce', 'criticized': 'criticize', 'haunted': 'haunt', 'report': 'report', 'undressed': 'undress', 'learned': 'learn', 'runs': 'run', 'libels': 'libel', 'pressed': 'press', 'seeks': 'seek', 'release': 'release', 'complimenting': 'compliment', 'steal': 'steal', '~blame': '~blame', 'thanks': 'thank', 'respond': 'respond', 'blew': 'blow', 'wooped': '', 'observes': 'observe', 'prejudging': 'prejudge', 'testing': 'test', '~harm': '~harm', 'resist': 'resist', 'depends': 'depend', 'misjudged': 'misjudge', 'fail': 'fail', 'disturbing': 'disturb', 'tortured': 'torture', 'said': 'say', 'interviewing': 'interview', 'rings': 'ring', 'startle': 'startle', 'pets': 'pet', 'scorn': 'scorn', 'shaves': 'shave', 'approach': 'approach', '~smell': '~smell', 'terms': 'term', 'rolled': 'roll', 'whiffed': 'whiff', 'schooled': 'school', '~met': '~meet', 'enters': 'enter', 'wear': 'wear', 'blitzed': 'blitz', 'picking': 'pick', 'overestimated': 'overestimate', 'electing': 'elect', 'faced': 'face', 'received': 'receive', 'protect': 'protect', 'pleasuring': 'pleasure', 'met': 'meet', 'paralyzing': 'paralyze', 'undercharged': 'undercharge', 'receives': 'receive', 'surprises': 'surprise', 'sympathised': 'sympathise', 'argue': 'argue', 'confronted': 'confront', 'asked': 'ask', 'vexed': 'vex', 'appeared': 'appear', 'confide': 'confide', 'vexes': 'vex', 'fondled': 'fondle', 'trust': 'trust', 'heals': 'heal', 'apprehended': 'apprehend', 'speak': 'speak', 'recognises': 'recognise', 'asks': 'ask', 'condemned': 'condemn', 'criticised': 'criticise', 'startled': 'startle', 'interest': 'interest', 'blowed': 'blow', 'entered': 'enter', 'threw': 'throw', 'life': '', 'harangues': 'harangue', 'spit': 'spit', 'attacked': 'attack', 'pecked': 'peck', 'dismiss': 'dismiss', 'disgruntle': 'disgruntle', '~believe': '~believe', 'dote': 'dote', 'budged': 'budge', 'catch': 'catch', 'worked': 'work', '~eradicate': '~eradicate', 'stomped': 'stomp', 'reverted': 'revert', 'decapitated': 'decapitate', 'womble': '', 'hates': 'hate', 'stopping': 'stop', 'aid': 'aid', 'murders': 'murder', 'leaves': 'leave', 'remembering': 'remember', 'stink': 'stink', 'climbed': 'climb', 'played': 'play', 'trustes': 'trust', 'is': 'be', 'dumped': 'dump', 'defeated': 'defeat', 'dazzled': 'dazzle', 'obeying': 'obey', 'taunts': 'taunt', 'ordered': 'order', 'dazzles': 'dazzle', 'uplift': 'uplift', 'trusted': 'trust', 'confirmed': 'confirm', '~affect': '~affect', 'perform': 'perform', 'make': 'make', 'wound': 'wound', 'backed': 'back', 'pardoning': 'pardon', '~answered': '~answer', 'disparaged': 'disparage', 'confronting': 'confront', 'toasted': 'toast', 'tricking': 'trick', 'blames': 'blame', 'hang': 'hang', 'greeted': 'greet', 'delight': 'delight', 'nurtured': 'nurture', 'blamed': 'blame', 'kid': 'kid', 'kept': 'keep', 'possessed': 'possess', 'failing': 'fail', 'beamed': 'beam', 'berate': 'berate', '~forgive': '~forgive', 'contact': 'contact', 'mother': 'mother', 'hearts': 'heart', 'left': 'leave', 'spurred': 'spur', 'appease': 'appease', 'departed': 'depart', 'quoted': 'quote', 'unfollow': 'unfollow', 'bruise': 'bruise', 'identify': 'identify', 'transforms': 'transform', 'provokes': 'provoke', 'adding': 'add', 'chided': 'chide', 'nudge': 'nudge', '~adopted': '~adopt', 'had': 'have', 'reuniting': 'reunite', 'exalt': 'exalt', 'shout': 'shout', 'belongs': 'belong', 'save': 'save', 'expelled': 'expel', 'trashed': 'trash', 'photographed': 'photograph', 'mocked': 'mock', 'boxed': 'box', '~fail': '~fail', 'looks': 'look', 'injuring': 'injure', 'judge': 'judge', 'dreamt': 'dream', 'shadow': 'shadow', 'burns': 'burn', 'burnt': 'burn', 'advanced': 'advance', 'desire': 'desire', 'nauseate': 'nauseate', 'blacklisted': 'blacklist', 'deafened': 'deafen', 'contradict': 'contradict', 'hunt': 'hunt', 'remind': 'remind', 'misled': 'mislead', 'confront': 'confront', 'hung': 'hang', '~forget': '~forget', 'gifted': 'gift', 'honored': 'honor', 'snub': 'snub', 'deal': 'deal', 'flatter': 'flatter', 'crown': 'crown', 'accost': 'accost', 'gawked': 'gawk', 'hassle': 'hassle', 'flatten': 'flatten', 'invoice': 'invoice', 'escape': 'escape', 'pain': 'pain', 'bore': 'bore', 'outgrew': 'outgrow', 'congratulate': 'congratulate', 'spazzed': 'spaz', 'killing': 'kill', 'asking': 'ask', 'honoured': 'honour', 'summoned': 'summon', 'denied': 'deny', 'beating': 'beat', 'pinched': 'pinch', 'gank': 'gank', 'burn': 'burn', 'disappeared': 'disappear', 'idolized': 'idolize', 'pinches': 'pinch', 'replying': 'reply', 'takes': 'take', 'meow': 'meow', 'ribs': 'rib', '~need': '~need', 'accepts': 'accept', 'choke': 'choke', 'surround': 'surround', 'misleading': 'mislead', 'impersonated': 'impersonate', 'stoked': 'stoke', 'cherish': 'cherish', 'raised': 'raise', 'froze': 'freeze', 'lied': 'lie', 'pays': 'pay', 'sparing': 'spare', 'delighted': 'delight', 'balances': 'balance', 'undermining': 'undermine', 'turfed': 'turf', 'raises': 'raise', 'wrap': 'wrap', 'shoots': 'shoot', 'frightened': 'frighten', 'stumble': 'stumble', 'rely': 'rely', 'despised': 'despise', 'stereotype': 'stereotype', 'wailed': 'wail', 'implore': 'implore', 'support': 'support', 'raped': 'rape', 'forbad': 'forbid', 'stuck': 'stick', 'fought': 'fight', 'despises': 'despise', 'cryed': 'cry', 'rapes': 'rape', 'untie': 'untie', 'was': 'be', 'war': 'war', 'launching': 'launch', 'grooms': 'groom', 'underestimated': 'underestimate', 'beshit': '', 'heal': 'heal', 'warred': 'war', '~thanked': '~thank', 'hear': 'hear', 'mooned': 'moon', 'survive': 'survive', 'astonished': 'astonish', 'sustained': 'sustain', 'nodded': 'nod', 'humiliate': 'humiliate', 'reset': 'reset', 'duel': 'duel', 'ruined': 'ruin', 'adore': 'adore', 'torturing': 'torture', 'scream': 'scream', 'slaughtered': 'slaughter', 'fulfills': 'fulfill', 'promises': 'promise', 'adopt': 'adopt', 'disgrace': 'disgrace', 'tolerated': 'tolerate', 'unnerve': 'unnerve', 'soothe': 'soothe', 'dashed': 'dash', 'promised': 'promise', 'annoying': 'annoy', 'animate': 'animate', 'shit': 'shit', '~repay': '~repay', 'discriminate': 'discriminate', 'clings': 'cling', 'handed': 'hand', 'despising': 'despise', 'meows': 'meow', 'interested': 'interest', 'shittalked': 'shittalk', 'vanished': 'vanish', 'smell': 'smell', 'scored': 'score', 'subsidize': 'subsidize', 'surprise': 'surprise', 'felt': 'felt', 'convincing': 'convince', 'maimed': 'maim', 'fell': 'fell', 'died': 'die', 'babysitting': '', 'jacked': 'jack', 'cheated': 'cheat', 'foresook': '', 'assume': 'assume', 'exalts': 'exalt', 'proposed': 'propose', 'sniffed': 'sniff', 'longed': 'long', 'cautioning': 'caution', 'push': 'push', 'restored': 'restore', 'dotes': 'dote', 'befriend': 'befriend', 'broke': 'break', 'dance': 'dance', 'rob': 'rob', 'bombed': 'bomb', 'leads': 'lead', 'tusting': '', 'disobeys': 'disobey', 'hijacked': 'hijack', 'depend': 'depend', 'fancies': 'fancy', 'outplayed': 'outplay', 'answered': 'answer', 'charge': 'charge', 'praised': 'praise', 'promoting': 'promote', 'discovering': 'discover', 'disapproved': 'disapprove', 'agreed': 'agree', 'persevere': 'persevere', 'supported': 'support', 'inciting': 'incite', 'huged': 'hug', 'defying': 'defy', 'masturbate': 'masturbate', 'advised': 'advise', 'cook': 'cook', 'forgiving': 'forgive', 'eats': 'eat', 'discrimate': '', 'perceived': 'perceive', 'evaded': 'evade', 'presented': 'present', 'did': 'do', 'turns': 'turn', 'dig': 'dig', 'forgets': 'forget', 'leave': 'leave', '~recognized': '~recognize', 'perceives': 'perceive', 'round': 'round', 'shave': 'shave', 'talked': 'talk', 'says': 'say', 'regret': 'regret', 'irritates': 'irritate', 'discover': 'discover', 'cost': 'cost', 'comforting': 'comfort', 'mentored': 'mentor', 'penetrated': 'penetrate', 'irritated': 'irritate', 'focked': '', 'curse': 'curse', 'appear': 'appear', 'deluded': 'delude', 'feat': '', 'favour': 'favour', 'pleased': 'please', 'suspect': 'suspect', 'goes': 'go', 'bombing': 'bomb', 'shared': 'share', 'appeal': 'appeal', 'growls': 'growl', 'supporting': 'support', 'channeled': 'channel', 'honour': 'honour', 'persecutes': 'persecute', 'understanding': 'understand', 'abandon': 'abandon', 'entertain': 'entertain', 'persecuted': 'persecute', 'refused': 'refuse', 'teaches': 'teach', '~assisted': '~assist', 'change': 'change', 'wait': 'wait', 'sending': 'send', 'overtipped': '', 'snubbed': 'snub', 'studied': 'study', 'funded': 'fund', 'bow': 'bow', 'thrashed': 'thrash', 'upstaging': 'upstage', 'bangs': 'bang', 'studies': 'study', 'reclaim': 'reclaim', 'rededicate': 'rededicate', 'tasks': 'task', 'elect': 'elect', 'shelled': 'shell', 'besought': 'beseech', 'lending': 'lend', 'shaming': 'shame', 'betraying': 'betray', 'penalized': 'penalize', 'scam': 'scam', 'quenching': 'quench', 'loveing': 'love', 'opposes': 'oppose', 'handled': 'handle', 'captivate': 'captivate', 'visit': 'visit', 'msn': '', 'live': 'live', 'opposed': 'oppose', 'enriched': 'enrich', 'associated': 'associate', 'cooperated': 'cooperate', 'loving': 'love', 'scratched': 'scratch', 'introducing': 'introduce', 'teased': 'tease', 'dislikes': 'dislike', 'teases': 'tease', 'degrade': 'degrade', 'scratches': 'scratch', 'fingered': 'finger', 'fly': 'fly', 'valued': 'value', 'decked': 'deck', 'avoiding': 'avoid', 'believes': 'believe', 'attacks': 'attack', 'believed': 'believe', 'making': 'make', 'bites': 'bite', 'disowned': 'disown', 'admired': 'admire', 'rebuffed': 'rebuff', 'hears': 'hear', 'fuck': 'fuck', 'heard': 'hear', 'stroke': 'stroke', 'sued': 'sue', 'dropped': 'drop', 'hides': 'hide', 'allowed': 'allow', 'provoke': 'provoke', 'stole': 'steal', 'listens': 'listen', 'reprove': 'reprove', 'ping': 'ping', 'write': 'write', 'dined': 'dine', 'swore': 'swear', '~idolise': '~idolise', 'speaks': 'speak', 'begs': 'beg', 'snaps': 'snap', 'whacked': 'whack', 'sacrifice': 'sacrifice', 'fed': 'feed', 'needs': 'need', 'disgusted': 'disgust', 'informs': 'inform', 'meddled': 'meddle', 'depriving': 'deprive', '~leaves': '~leave', 'mocks': 'mock', '~phoned': '~phone', 'suck': 'suck', 'antagonise': 'antagonise', 'pressuring': 'pressure', 'stroked': 'stroke', 'remember': 'remember', 'amuse': 'amuse', 'inform': 'inform', 'nosed': 'nose', 'dishonoured': 'dishonour', 'deceive': 'deceive', 'offend': 'offend', 'talk': 'talk', 'refund': 'refund', 'acts': 'act', 'pointed': 'point', 'wishing': 'wish', 'aiding': 'aid', 'hiring': 'hire', 'yearn': 'yearn', 'stayed': 'stay', 'shake': 'shake', 'argued': 'argue', 'equip': 'equip', 'worship': 'worship', 'blocked': 'block', 'thank': 'thank', 'acknowledge': 'acknowledge', 'brained': 'brain', 'abhorred': 'abhor', 'inflicted': 'inflict', 'petition': 'petition', 'happened': 'happen', 'emailed': 'email', '~conquer': '~conquer', 'telled': 'tell', 'reject': 'reject', 'feelin': '', 'interview': 'interview', 'conquer': 'conquer', 'not': '', '': 'kill', 'possess': 'possess', 'escorting': 'escort', 'shouted': 'shout', 'name': 'name', 'stabilize': 'stabilize', 'lies': 'lie', 'ribbed': 'rib', 'drop': 'drop', 'wrote': 'write', 'peered': 'peer', 'intrigued': 'intrigue', 'rock': 'rock', 'scolded': 'scold', 'liberating': 'liberate', 'waved': 'wave', 'married': 'marry', 'fired': 'fire', 'challenged': 'challenge', 'challenges': 'challenge', '~dominate': '~dominate', 'fires': 'fire', 'catching': 'catch', 'sponsor': 'sponsor', 'preaching': 'preach', 'counteract': 'counteract', 'avoided': 'avoid', 'sustains': 'sustain', '~answer': '~answer', '~knew': '~know', 'infuriated': 'infuriate', 'worshiped': 'worship', 'abide': 'abide', 'infuriates': 'infuriate', 'attracted': 'attract', 'condemns': 'condemn', 'appointed': 'appoint', 'nned': '', 'bugging': 'bug', 'correct': 'correct', 'ostracise': 'ostracise', 'moooves': '', 'caressed': 'caress', 'disrespect': 'disrespect', 'bumps': 'bump', 'scarred': 'scar', 'limps': 'limp', 'care': 'care', 'envies': 'envy', 'advance': 'advance', '~go': '~go', 'kajiao': '', 'dunno': '', 'interacted': 'interact', 'turn': 'turn', 'marauded': 'maraud', 'think': 'think', 'waited': 'wait', 'spotted': 'spot', 'suspend': 'suspend', 'saving': 'save', '~live': '~live', 'surviving': 'survive', 'ignored': 'ignore', 'question': 'question', 'bullshits': 'bullshit', 'tasered': '', 'vote': 'vote', 'ring': 'ring', 'fight': 'fight', 'open': 'open', 'appealed': 'appeal', 'zap': 'zap', 'squashed': 'squash', 'given': 'give', 'checked': 'check', 'spurned': 'spurn', 'caught': 'catch', 'slept': 'sleep', 'returns': 'return', '~love': '~love', 'terrifying': 'terrify', 'stuffed': 'stuff', 'cite': 'cite', 'gives': 'give', 'seduced': 'seduce', 'hug': 'hug', 'massaged': 'massage', 'appreciates': 'appreciate', 'telephoned': 'telephone', 'released': 'release', 'eyed': 'eye', 'slashed': 'slash', 'fooled': 'fool', 'eliminated': 'eliminate', 'representing': 'represent', 'subbed': 'sub', 'feeds': 'feed', 'require': 'require', 'recruit': 'recruit', 'dissed': 'diss', 'protected': 'protect', 'disrespects': 'disrespect', 'were': 'be', '~leave': '~leave', 'and': '', 'lick': 'lick', 'tasted': 'taste', 'remained': 'remain', 'appreciate': 'appreciate', 'turned': 'turn', 'slap': 'slap', 'straddles': 'straddle', 'say': 'say', 'slam': 'slam', 'anger': 'anger', 'saw': 'saw', 'sat': 'sit', 'mislead': 'mislead', 'clung': 'cling', 'luring': 'lure', 'knead': 'knead', 'isolate': 'isolate', 'instructed': 'instruct', 'take': 'take', 'destroy': 'destroy', 'altered': 'alter', 'opposite': '', 'knew': 'know', 'paid': 'pay', 'falls': 'fall', 'assault': 'assault', '~emailed': '~email', '~understand': '~understand', 'luv': '', 'surprising': 'surprise', 'energize': 'energize', 'sassed': 'sass', 'slaves': 'slave', 'butchered': 'butcher', 'sasses': 'sass', 'vetted': 'vet', 'shot': 'shoot', 'show': 'show', 'cheat': 'cheat', 'infuriate': 'infuriate', 'discovered': 'discover', 'hack': 'hack', 'corner': 'corner', 'curled': 'curl', 'aint': '', 'slow': 'slow', 'finessing': '', 'believing': 'believe', 'cautioned': 'caution', 'resenting': 'resent', 'get': 'get', 'expects': 'expect', 'cursing': 'curse', 'hailed': 'hail', 'honours': 'honour', '~recognises': '~recognise', 'celebrate': 'celebrate', 'reveal': 'reveal', 'beseech': 'beseech', 'joked': 'joke', 'imprison': 'imprison', 'worried': 'worry', 'whipped': 'whip', 'baits': 'bait', 'worries': 'worry', 'expceted': '', 'communicated': 'communicate', 'reveals': 'reveal', 'chawp': '', 'burst': 'burst', 'raged': 'rage', 'elected': 'elect', 'eliminating': 'eliminate', 'murdered': 'murder', 'aroused': 'arouse', 'satisfies': 'satisfy', 'encouraged': 'encourage', '~regard': '~regard', 'fails': 'fail', 'enlightening': 'enlighten', 'belittles': 'belittle', 'jumped': 'jump', 'review': 'review', 'justifies': 'justify', 'label': 'label', 'invokes': 'invoke', 'hiss': 'hiss', 'chews': 'chew', 'enjoys': 'enjoy', 'reading': 'read', 'fascinates': 'fascinate', 'forsake': 'forsake', 'notice': 'notice', '~give': '~give', 'friended': '', 'signaled': 'signal', 'blame': 'blame', 'sacked': 'sack', 'hurts': 'hurt', 'spark': 'spark', 'comb': 'comb', 'come': 'come', 'assess': 'assess', 'stun': 'stun', 'conversed': 'converse', 'spared': 'spare', 'according': 'accord', 'enabling': 'enable', 'pray': 'pray', 'dated': 'date', 'comes': 'come', 'cornered': 'corner', 'spoil': 'spoil', 'mails': 'mail', 'spank': 'spank', 'exploit': 'exploit', '~stop': '~stop', 'learning': 'learn', 'guesses': 'guess', 'vanquished': 'vanquish', '~outlast': '~outlast', 'considering': 'consider', 'punishes': 'punish', 'cares': 'care', '~acknowledged': '~acknowledge', 'informed': 'inform', 'cared': 'care', 'punished': 'punish', 'entices': 'entice', '~die': '~die', 'ultis': '', 'bullshit': 'bullshit', 'watgh': '', 'educated': 'educate', 'robbed': 'rob', 'offered': 'offer', 'blessing': 'bless', 'squash': 'squash', 'wounds': 'wound', 'mocking': 'mock', 'observe': 'observe', 'bollocked': '', 'paying': 'pay', 'chooing': '', 'disapeared': '', 'trick': 'trick', 'cure': 'cure', 'joke': 'joke', 'squeezed': 'squeeze', 'profiled': 'profile', 'endured': 'endure', 'invited': 'invite', 'punches': 'punch', 'engaged': 'engage', 'outran': 'outrun', 'punched': 'punch', 'commanded': 'command', 'reviles': 'revile', 'thrills': 'thrill', '~like': '~like', '~had': '~have', 'threatens': 'threaten', 'pester': 'pester', 'reminded': 'remind', 'busted': 'bust', 'pad': 'pad', 'angered': 'anger', 'scooped': 'scoop', 'agitated': 'agitate', 'whomps': 'whomp', 'motioned': 'motion', 'stepped': 'step', 'petted': 'pet', 'defy': 'defy', 'assist': 'assist', 'noticing': 'notice', 'protested': 'protest', 'scorned': 'scorn', 'complained': 'complain', 'break': 'break', 'drain': 'drain', 'sheeep': '', 'amazes': 'amaze', 'maltreated': 'maltreat', 'bang': 'bang', 'without': '', 'grinned': 'grin', 'relied': 'rely', 'reward': 'reward', 'amazed': 'amaze', 'charged': 'charge', 'slugged': 'slug', 'sprayed': 'spray', 'sights': 'sight', 'growled': 'growl', 'kill': 'kill', 'disperse': 'disperse', 'objectifying': 'objectify', 'touch': 'touch', 'guides': 'guide', 'captured': 'capture', 'blow': 'blow', 'renewed': 'renew', 'deceiving': 'deceive', 'grounded': 'ground', 'ambushed': 'ambush', 'bestirred': 'bestir', 'blog': 'blog', 'lets': 'let', 'pesters': 'pester', 'complements': 'complement', '~corrected': '~correct', 'struck': 'strike', 'sucked': 'suck', 'grip': 'grip', 'starving': 'starve', 'hover': 'hover', 'around': '', 'kills': 'kill', 'read': 'read', 'stung': 'sting', 'mob': 'mob', 'accepted': 'accept', 'disappointed': 'disappoint', 'pinged': 'ping', 'ruled': 'rule', 'championing': 'champion', 'terrorize': 'terrorize', 'greeting': 'greet', 'serves': 'serve', 'benefit': 'benefit', 'served': 'serve', 'endorsed': 'endorse', 'shunned': 'shun', 'picture': 'picture', 'hacks': 'hack', 'respect': 'respect', 'thinks': 'think', 'slappped': '', 'nood': '', 'bless': 'bless', 'confirm': 'confirm', 'stops': 'stop', 'resonate': 'resonate', 'picks': 'pick', 'refer': 'refer', 'terrifies': 'terrify', 'destroys': 'destroy', 'welcome': 'welcome', 'annihilated': 'annihilate', 'rosewithin': '', 'equips': 'equip', 'breastfeed': 'breastfeed', 'nails': 'nail', 'communicate': 'communicate', 'confides': 'confide', 'seducing': 'seduce', 'terrified': 'terrify', 'strangled': 'strangle', 'throw': 'throw', 'on': '', 'tease': 'tease', 'roar': 'roar', 'smear': 'smear', 'informing': 'inform', '~own': '~own', 'beseeched': 'beseech', 'stand': 'stand', 'act': 'act', 'internalize': 'internalize', 'eluded': 'elude', 'freeing': 'free', 'curses': 'curse', 'befooled': 'befool', 'blessed': 'bless', 'sabbee': '', 'strip': 'strip', 'unnerves': 'unnerve', '~forgot': '~forget', 'stare': 'stare', 'loathed': 'loathe', '~charge': '~charge', 'betrays': 'betray', 'handcuffed': 'handcuff', 'forbade': 'forbid', 'complete': 'complete', 'fricken': '', 'strikes': 'strike', 'ragged': 'rag', 'squeze': '', 'with': '', 'buying': 'buy', 'abused': 'abuse', 'pull': 'pull', 'hire': 'hire', 'annihilate': 'annihilate', 'rescuing': 'rescue', 'flirt': 'flirt', 'abuses': 'abuse', 'define': 'define', 'agree': 'agree', '~add': '~add', 'wants': 'want', 'subdue': 'subdue', 'frighten': 'frighten', 'blesses': 'bless', 'forgot': 'forget', 'am': 'be', 'watches': 'watch', 'examine': 'examine', 'at': '', 'walks': 'walk', 'watched': 'watch', 'amused': 'amuse', 'describs': '', 'film': 'film', 'fill': 'fill', 'uplifts': 'uplift', 'stumbled': 'stumble', 'deserve': 'deserve', 'floored': 'floor', 'repent': 'repent', 'slew': 'slew', 'painted': 'paint', 'sledges': 'sledge', 'fools': 'fool', 'steered': 'steer', 'requested': 'request', 'shelter': 'shelter', 'refunded': 'refund', 'drift': 'drift', 'flattened': 'flatten', 'recognise': 'recognise', 'included': 'include', 'lving': '', 'resembled': 'resemble', 'booked': 'book', 'calls': 'call', 'invest': 'invest', 'having': 'have', 'weth': '', 'mimic': 'mimic', 'paced': 'pace', 'doubted': 'doubt', 'embracing': 'embrace', 'humoring': 'humor', 'burdening': 'burden', 'forget': 'forget', '~chose': '~choose', 'alerting': 'alert', 'generalize': 'generalize', 'talks': 'talk', 'follow': 'follow', 'mooning': 'moon', 'referring': 'refer', 'reprobates': 'reprobate', 'to': '', 'program': 'program', 'smile': 'smile', 'correcting': 'correct', 'returned': 'return', 'focus': 'focus', '~judge': '~judge', 'scout': 'scout', 'fall': 'fall', 'witted': '', 'condition': 'condition', 'treating': 'treat', 'accompanying': 'accompany', 'drugged': 'drug', 'dodged': 'dodge', 'reminding': 'remind', 'sang': 'sing', 'rebuffs': 'rebuff', 'havenow': '', 'shanghaied': 'shanghai', 'grabs': 'grab', 'healed': 'heal', 'rate': 'rate', 'knifed': 'knife', 'pass': 'pass', 'ksing': '', 'penalise': 'penalise', 'sue': 'sue', 'apologizes': 'apologize', 'stood': 'stand', 'witnessed': 'witness', 'fucks': 'fuck', '~be': '~be', 'crush': 'crush', 'apologized': 'apologize', 'frightens': 'frighten', 'nurse': 'nurse', 'dwells': 'dwell', 'empower': 'empower', 'responded': 'respond', 'answers': 'answer', 'plunders': 'plunder', 'praises': 'praise', 'drubbed': 'drub', 'slapping': 'slap', 'razz': 'razz', 'inspired': 'inspire', 'laved': 'lave', 'allows': 'allow', 'experience': 'experience', 'honoring': 'honor', 'horrified': 'horrify', 'pick': 'pick', 'supplicate': 'supplicate', 'raze': 'raze', 'inspires': 'inspire', 'followed': 'follow', '~heard': '~hear', 'texts': '', '~choose': '~choose', 'trained': 'train', 'beheld': 'behold', 'pulls': 'pull', 'select': 'select', 'barked': 'bark', 'pulverize': 'pulverize', 'proceed': 'proceed', 'injure': 'injure', 'enliven': 'enliven', 'faint': 'faint', 'irritate': 'irritate', 'decribs': '', 'splash': 'splash', 'wisit': '', 'rejoined': 'rejoin', 'kick': 'kick', 'hisses': 'hiss', '~identify': '~identify', 'knows': 'know', '~respect': '~respect', 'corrected': 'correct', 'goads': 'goad', 'stick': 'stick', 'hissed': 'hiss', 'mounted': 'mount', 'rips': 'rip', 'keeping': 'keep', 'include': 'include', 'squish': 'squish', 'created': 'create', 'sucks': 'suck', 'guards': 'guard', 'offended': 'offend', 'remain': 'remain', 'learn': 'learn', 'knocked': 'knock', 'upbraided': 'upbraid', 'advises': 'advise', 'embarrassing': 'embarrass', 'challenging': 'challenge', 'pushes': 'push', 'rejuvenated': 'rejuvenate', '~startled': '~startle', 'neglected': 'neglect', 'conspire': 'conspire', 'accept': 'accept', 'boycott': 'boycott', 'pushed': 'push', 'folleweth': '', 'protects': 'protect', 'elbowed': 'elbow', 'sense': 'sense', 'exclude': 'exclude', 'pong': '', 'disliked': 'dislike', 'hits': 'hit', 'bonded': 'bond', 'condemn': 'condemn', 'influenced': 'influence', 'dazzle': 'dazzle', 'engages': 'engage', 'breaking': 'break', 'goad': 'goad', 'dismissed': 'dismiss', 'cleansing': 'cleanse', 'untied': 'untie', 'deems': 'deem', 'worry': 'worry', 'cling': 'cling', 'hugs': 'hug', 'dismisses': 'dismiss', 'acknowledging': 'acknowledge', 'skratis': '', 'tried': 'try', 'glared': 'glare', 'emulate': 'emulate', 'sneak': 'sneak', 'questioning': 'question', 'reflect': 'reflect', 'waves': 'wave', 'pleaded': 'plead', 'prospecting': 'prospect', 'refuse': 'refuse', 'criticize': 'criticize', 'backstab': '', 'crowded': 'crowd', 'bugs': 'bug', 'loue': '', 'deserted': 'desert', 'renewing': 'renew', 'rebuked': 'rebuke', 'dread': 'dread', 'scaring': 'scare', 'reshape': 'reshape', 'retaliate': 'retaliate', 'replied': 'reply', 'help': 'help', 'displease': 'displease', 'winged': 'wing', 'eludes': 'elude', 'held': 'hold', 'quarrels': 'quarrel', 'suffer': 'suffer', 'agrees': 'agree', 'trouble': 'trouble', 'disagreed': 'disagree', 'licks': 'lick', 'mistreated': 'mistreat', 'satsify': '', 'assaulting': 'assault', 'solving': 'solve', 'disagrees': 'disagree', 'fines': 'fine', 'underestimate': 'underestimate', '~pay': '~pay', 'hurting': 'hurt', 'pleads': 'plead', 'return': 'return', 'razzes': 'razz', 'sucker': '', 'smothering': 'smother', 'awarding': 'award', 'reflected': 'reflect', 'obeyed': 'obey', 'motivates': 'motivate', 'fancy': 'fancy', 'belittle': 'belittle', 'stoned': 'stone', '~supported': '~support', 'complain': 'complain', 'slighted': 'slight', 'groped': 'grope', 'prayed': 'pray', 'evade': 'evade', 'yearns': 'yearn', 'stopped': 'stop', 'reassures': 'reassure', 'goofs': 'goof', '~remember': '~remember', 'referred': 'refer', 'embarass': '', 'begged': 'beg', 'pamper': 'pamper', 'house': 'house', 'exasperated': 'exasperate', 'used': 'use', 'expect': 'expect', 'suspecting': 'suspect', 'organised': 'organise', 'terrify': 'terrify', '~call': '~call', 'taunted': 'taunt', 'missed': 'miss', 'disbelieved': 'disbelieve', 'miss': 'miss', 'surrounded': 'surround', 'mattered': 'matter', 'overcharging': 'overcharge', 'trusts': 'trust', 'misses': 'miss', 'sustain': 'sustain', 'outrun': 'outrun', 'denounces': 'denounce', 'dunk': 'dunk', 'bully': 'bully', 'found': 'found', 'favored': 'favor', 'forgive': 'forgive', 'qualify': 'qualify', 'ask': 'ask', 'teach': 'teach', 'reproach': 'reproach', 'bash': 'bash', 'blister': 'blister', 'bumped': 'bump', 'benefits': 'benefit', '~save': '~save', 'needing': 'need', 'sicken': 'sicken', 'prospered': 'prosper', 'leading': 'lead', 'throws': 'throw', 'feed': 'feed', 'embraces': 'embrace', 'gazed': 'gaze', 'stabs': 'stab', 'feel': 'feel', 'relate': 'relate', 'bullies': 'bully', 'disregarded': 'disregard', 'feedes': 'feed', 'done': 'do', 'embraced': 'embrace', 'aggros': '', 'bullied': 'bully', 'fearing': 'fear', 'passes': 'pass', 'boating': 'boat', 'divorce': 'divorce', 'interviews': 'interview', 'threatening': 'threaten', 'paint': 'paint', 'bum': 'bum', 'passed': 'pass', 'kidded': 'kid', 'shifted': 'shift', 'relies': 'rely', 'bowed': 'bow', 'selling': 'sell', 'treasured': 'treasure', 'trapped': 'trap', 'exploded': 'explode', 'convinces': 'convince', 'interviewed': 'interview', '~reply': '~reply', 'consult': 'consult', 'sold': 'sell', 'believe': 'believe', 'stirs': 'stir', '~foul': '~foul', 'assaulted': 'assault', 'compliments': 'compliment', 'inducted': 'induct', 'disrespected': 'disrespect', 'teazes': '', 'defends': 'defend', 'pampered': 'pamper', 'stalk': 'stalk', 'insulted': 'insult', 'remembers': 'remember', 'fights': 'fight', 'ogled': 'ogle', 'reprobate': 'reprobate', 'showers': 'shower', 'orders': 'order', 'sell': 'sell', 'lie': 'lie', 'built': 'build', '~reached': '~reach', 'flaming': 'flame', 'honors': 'honor', 'walk': 'walk', 'recognizing': 'recognize', 'humanize': 'humanize', 'build': 'build', 'duped': 'dupe', 'aggravating': 'aggravate', 'hearkened': 'hearken', 'brace': 'brace', 'seized': 'seize', 'play': 'play', 'added': 'add', 'quote': 'quote', 'reach': 'reach', 'educate': 'educate', 'exempted': 'exempt', 'plunder': 'plunder', 'endangering': 'endanger', 'charm': 'charm', 'fellowed': '', 'nothing': '', 'accepting': 'accept', 'stands': 'stand', '~begrudged': '~begrudge', 'understands': 'understand', 'wuvs': '', 'cover': 'cover', 'attacking': 'attack', 'joining': 'join', 'stalked': 'stalk', 'despise': 'despise', 'ennoble': 'ennoble', 'amaze': 'amaze', 'stunned': 'stun', 'mistreats': 'mistreat', 'hugging': 'hug', 'defended': 'defend', 'cruised': 'cruise', 'giggled': 'giggle', 'fining': 'fine', 'fine': 'fine', 'find': 'find', 'faces': 'face', 'distressing': 'distress', 'tahnks': '', 'depended': 'depend', 'ruin': 'ruin', 'failed': 'fail', 'saveth': '', 'criticising': 'criticise', 'circle': 'circle', 'loved': 'love', 'believeth': '', 'hit': 'hit', 'invoke': 'invoke', 'quizzes': 'quiz', 'banned': 'ban', 'resent': 'resent', 'feels': 'feel', 'grew': 'grow', 'hid': 'hide', 'preparing': 'prepare', 'hustled': 'hustle', 'nagging': 'nag', 'judged': 'judge', 'quizzed': 'quiz', 'catches': 'catch', 'querying': 'query', 'commiserated': 'commiserate', 'pleasures': '', 'cry': 'cry', '~compromise': '~compromise', 'spiked': 'spike', 'untying': 'untie', 'repulsed': 'repulse', 'approaching': 'approach', 'set': 'set', 'dump': 'dump', 'drafted': 'draft', 'feares': 'fear', 'uses': 'use', 'venerate': 'venerate', 'are': 'be', 'close': 'close', 'supplicated': 'supplicate', 'comfort': 'comfort', 'feared': 'fear', 'learnt': 'learn', 'visiting': 'visit', 'nailed': 'nail', 'please': 'please', 'slapped': 'slap', 'soaped': 'soap', 'harrassing': '', 'grunts': 'grunt', 'thanksed': '', 'burned': 'burn', 'compliment': 'compliment', 'piss': 'piss', 'manipulates': 'manipulate', 'vindicated': 'vindicate', 'creating': 'create', 'pisses': 'piss', 'complement': 'complement', 'oppress': 'oppress', 'betrayed': 'betray', 'accuse': 'accuse', '~heal': '~heal', 'last': 'last', 'adores': 'adore', 'contemplate': 'contemplate', '~tell': '~tell', '~contacted': '~contact', 'chastising': 'chastise', 'adored': 'adore', 'blazed': 'blaze', 'became': 'become', 'finds': 'find', '~hear': '~hear', 'llub': '', 'liked': 'like', 'consume': 'consume', 'point': 'point', 'acted': 'act', 'recycling': 'recycle', 'smother': 'smother', 'befriending': 'befriend', 'dances': 'dance', 'likes': 'like', 'asserted': 'assert', 'lovees': 'love', 'distrusting': 'distrust', 'likey': '', 'decline': 'decline', 'raise': 'raise', 'dun': 'dun', 'create': 'create', 'overlook': 'overlook', 'appears': 'appear', 'convicted': 'convict', 'respecting': 'respect', 'baptizing': 'baptize', 'collected': 'collect', 'threaten': 'threaten', 'brick': '', 'illumines': 'illumine', 'meeting': 'meet', 'delights': 'delight', 'pm': '', 'lived': 'live', 'raced': 'race', 'fire': 'fire', 'infect': 'infect', 'revile': 'revile', 'lives': 'live', 'demand': 'demand', 'resisted': 'resist', '~loved': '~love', 'presses': 'press', 'misunderstands': 'misunderstand', 'look': 'look', 'animates': 'animate', 'pampers': 'pamper', 'admire': 'admire', 'forgetting': 'forget', 'phuck': '', 'caress': 'caress', 'enact': 'enact', 'licked': 'lick', 'guide': 'guide', 'indulging': 'indulge', 'owed': 'owe', 'smacked': 'smack', 'mistreat': 'mistreat', 'overlooked': 'overlook', 'leans': 'lean', 'encountered': 'encounter', 'awakening': 'awaken', 'owes': 'owe', 'rib': 'rib', 'chase': 'chase', 'disillusioning': 'disillusion', 'remonstrated': 'remonstrate', 'grant': 'grant', 'belong': 'belong', '~fuck': '~fuck', 'authenticates': 'authenticate', 'copying': 'copy', 'dishonouring': 'dishonour', 'advise': 'advise', 'strips': 'strip', 'praising': 'praise', 'birthed': 'birth', 'tarried': 'tarry', 'helped': 'help', 'moving': 'move', '~shop': '~shop', 'nickname': 'nickname', 'canned': 'can', 'task': 'task', 'guarantee': 'guarantee', 'craved': 'crave', 'flirts': 'flirt', 'tase': '', 'dared': 'dare', 'cheer': 'cheer', 'sneered': 'sneer', 'withdraw': 'withdraw', 'savvy': 'savvy', 'signalled': 'signal', 'spend': 'spend', 'know': 'know', 'watchin': '', 'distracting': 'distract', 'shape': 'shape', 'using': 'use', 'love': 'love', 'letting': 'let', 'cut': 'cut', 'bloodying': 'bloody', 'cuffs': 'cuff', 'hated': 'hate', 'excites': 'excite', 'brutalise': 'brutalise', 'wakens': 'waken', 'exhilarate': 'exhilarate', 'questioned': 'question', 'tormented': 'torment', 'excited': 'excite', 'surprised': 'surprise', 'applauded': 'applaud', 'manage': 'manage', 'vindicate': 'vindicate', 'evaluate': 'evaluate', 'bid': 'bid', 'saluted': 'salute', 'verbosely': '', 'finding': 'find', 'bit': 'bite', 'defied': 'defy', 'knock': 'knock', 'lost': 'lose', 'follows': 'follow', 'ignore': 'ignore', 'collect': 'collect', 'distrust': 'distrust', 'continue': 'continue', 'provoking': 'provoke', 'stings': 'sting', 'scare': 'scare', '~abuse': '~abuse', 'infecting': 'infect', 'spring': 'spring', 'back': 'back', 'outnumber': 'outnumber', 'understood': 'understand', 'entwining': 'entwine', 'accelerate': 'accelerate', '~look': '~look', 'delivered': 'deliver', 'pet': 'pet', 'affects': 'affect', 'behave': 'behave', 'slash': 'slash', 'pee': 'pee', 'invade': 'invade', 'be': 'be', 'berated': 'berate', 'run': 'run', 'remembered': 'remember', 'jumps': 'jump', 'dictates': 'dictate', 'sting': 'sting', 'deesiao': '', 'misbehave': 'misbehave', 'refuses': 'refuse', 'dictated': 'dictate', 'deserved': 'deserve', 'fouls': 'foul', 'firing': 'fire', 'deserver': '', 'deserves': 'deserve', 'ambush': 'ambush', 'hired': 'hire', 'greets': 'greet', 'forgave': 'forgive', '~threaten': '~threaten', 'wanna': '', 'bleeds': 'bleed', 'block': 'block', 'misplaced': 'misplace', 'seeing': 'see', 'scorns': 'scorn', 'harassed': 'harass', 'invading': 'invade', 'framed': 'frame', 'neglects': 'neglect', 'impressed': 'impress', '~called': '~call', 'masturbating': 'masturbate', 'bores': 'bore', 'cherished': 'cherish', 'marrying': 'marry', 'occupy': 'occupy', '~hate': '~hate', '~beat': '~beat', 'caresses': 'caress', 'impresses': 'impress', 'suit': 'suit', 'bored': 'bore', 'scared': 'scare', 'spat': 'spat', 'manufacture': 'manufacture', 'wna': '', 'invite': 'invite', 'relaxed': 'relax', 'hoped': 'hope', 'link': 'link', 'unblind': '', 'embarassed': '', 'harangue': 'harangue', 'raising': 'raise', 'posted': 'post', 'directed': 'direct', 'charmed': 'charm', 'redeemed': 'redeem', 'acidify': 'acidify', 'nestle': 'nestle', 'unlock': 'unlock', 'hospitalizing': 'hospitalize', 'called': 'call', 'yelled': 'yell', 'storing': 'store', 'freak': 'freak', 'flocked': 'flock', 'influence': 'influence', 'haunt': 'haunt', 'consulted': 'consult', 'warning': 'warn', 'home': 'home', 'wove': 'weave', 'denying': 'deny', 'nag': 'nag', '~turn': '~turn', 'swats': 'swat', 'fears': 'fear', 'backs': 'back', 'reimbursed': 'reimburse', 'mock': 'mock', '~hurt': '~hurt', 'smiles': 'smile', 'spurns': 'spurn', 'oblige': 'oblige', 'strums': 'strum', 'visits': 'visit', 'helping': 'help', 'sideline': 'sideline', 'allowing': 'allow', 'smiled': 'smile', '~see': '~see', 'desert': 'desert', 'structure': 'structure', 'forgives': 'forgive', 'rallied': 'rally', 'texted': '', 'reproached': 'reproach', 'disinherited': 'disinherit', 'rescued': 'rescue', 'humiliated': 'humiliate', 'walked': 'walk', 'appalling': 'appal', 'reproaches': 'reproach', 'decloak': '', 'dot': 'dot', 'banishing': 'banish', 'bribe': 'bribe', 'amuses': 'amuse', 'rescues': 'rescue', 'wrestle': 'wrestle', 'melts': 'melt', 'scratch': 'scratch', 'splashing': 'splash', 'beckons': 'beckon', 'go': 'go', 'query': 'query', '~know': '~know', '~want': '~want', 'hovered': 'hover', 'exterminate': 'exterminate', 'send': 'send', 'suits': 'suit', 'cradle': 'cradle', 'squeezing': 'squeeze', 'helps': 'help', 'excluded': 'exclude', 'suite': '', 'dislike': 'dislike', 'pleasing': 'please', 'sent': 'send', 'pay': 'pay', 'wished': 'wish', 'torture': 'torture', 'wave': 'wave', 'manipulated': 'manipulate', 'heckles': 'heckle', 'muzzled': 'muzzle', 'telling': 'tell', 'wipe': 'wipe', 'magic': '', 'marry': 'marry', 'shock': 'shock', 'resepect': '', 'try': 'try', 'race': 'race', 'freed': 'free', 'grawled': '', 'challenge': 'challenge', 'reactivating': 'reactivate', 'punishing': 'punish', 'tryust': '', 'waking': 'wake', 'jump': 'jump', 'imply': 'imply', 'picked': 'pick', 'nominates': 'nominate', 'click': 'click', 'poke': 'poke', 'plays': 'play', 'giving': 'give', 'assisted': 'assist', 'slight': 'slight', 'waiting': 'wait', '~destroy': '~destroy', 'worships': 'worship', 'harassing': 'harass', 'exercise': 'exercise', 'avoids': 'avoid', 'led': 'lead', 'chose': 'choose', 'desires': 'desire', 'upsetting': 'upset', 'gathered': 'gather', 'pushing': 'push', 'punch': 'punch', 'delivering': 'deliver', 'desired': 'desire', 'abducts': 'abduct', 'let': 'let', 'healing': 'heal', 'fulfill': 'fulfill', 'dissuade': 'dissuade', 'sing': 'sing', 'invented': 'invent', 'kidnapped': 'kidnap', 'deserts': 'desert', 'engage': 'engage', 'stalks': 'stalk', 'credits': 'credit', 'receive': 'receive', '~control': '~control', 'leaving': 'leave', 'defeat': 'defeat', 'climb': 'climb', 'behead': 'behead', 'makes': 'make', 'writes': 'write', 'ignores': 'ignore', 'suprising': '', 'named': 'name', 'heart': '', 'forbid': 'forbid', 'disobey': 'disobey', 'shoved': 'shove', 'offends': 'offend', 'distrusted': 'distrust', 'addressed': 'address', 'reprimands': 'reprimand', 'shoves': 'shove', 'manipulate': 'manipulate', 'bent': 'bend', 'use': 'use', 'cheered': 'cheer', 'from': '', 'remains': 'remain', 'congratulated': 'congratulate', '~saw': '~saw', 'doubt': 'doubt', 'congratulates': 'congratulate', 'betray': 'betray', '~cooperate': '~cooperate', 'started': 'start', 'becomes': 'become', 'impress': 'impress', 'train': 'train', 'billed': 'bill', 'loues': '', 'annoy': 'annoy', 'crosses': 'cross', 'rebelled': 'rebel', 'slaps': 'slap', 'ride': 'ride', 'disbelieve': 'disbelieve', '~disturb': '~disturb', 'praise': 'praise', 'meet': 'meet', 'nurture': 'nurture', 'drops': 'drop', 'fetch': 'fetch', 'performed': 'perform', 'control': 'control', 'tap': 'tap', 'admires': 'admire', 'links': 'link', 'invoices': 'invoice', 'rode': 'ride', 'sought': 'seek', 'paws': 'paw', 'rape': 'rape', '~ignore': '~ignore', 'daring': 'dare', 'sit': 'sit', 'destroying': 'destroy', 'holds': 'hold', 'carries': 'carry', 'fete': 'fete', 'clasping': 'clasp', 'obeys': 'obey', 'blocks': 'block', 'scammed': '', 'stop': 'stop', 'fouled': 'foul', '~skip': '~skip', 'chasing': 'chase', 'bind': 'bind', '~married': '~marry', 'budge': 'budge', 'scoop': 'scoop', 'prays': 'pray', 'allow': 'allow', 'bedew': 'bedew', 'hugges': '', 'waltzed': 'waltz', 'move': 'move', 'despiseth': '', 'hugged': 'hug', 'enclose': 'enclose', 'flopped': 'flop', 'mentioned': 'mention', 'vilify': 'vilify', 'thanking': 'thank', 'hunted': 'hunt', 'chosen': 'choose', 'spoiling': 'spoil', 'stalled': 'stall', 'covered': 'cover', '~hire': '~hire', 'flex': 'flex', 'practice': 'practice', 'devoured': 'devour', 'flew': 'fly', 'flout': 'flout', 'mention': 'mention', 'cutting': 'cut', 'bothering': 'bother', 'kiss': 'kiss', 'flee': 'flee', 'fled': 'flee', 'lpve': '', 'cursed': 'curse', 'overcharges': 'overcharge', 'admonished': 'admonish', 'thrill': 'thrill', 'irks': 'irk', 'warned': 'warn', 'demote': 'demote', 'speared': 'spear', 'identified': 'identify', 'sin': 'sin', 'admonishes': 'admonish', 'lobbies': 'lobby', 'illuminate': 'illuminate', 'doing': 'do', 'bums': 'bum', 'programmed': 'program', 'aggravated': 'aggravate', '~miss': '~miss', 'lobbied': 'lobby', 'measure': 'measure', 'separating': 'separate', 'satisfied': 'satisfy', 'annoys': 'annoy', 'respects': 'respect', 'harrased': '', 'mate': 'mate', 'performs': 'perform', 'supports': 'support', 'dive': 'dive', 'obsess': 'obsess', 'rewrote': 'rewrite', 'approached': 'approach', 'maintains': 'maintain', 'humiliating': 'humiliate', 'approaches': 'approach', 'thrust': 'thrust', 'embarrass': 'embarrass', 'bleed': 'bleed', 'befriended': 'befriend', 'reraised': '', 'mesmerized': 'mesmerize', 'dubbed': 'dub', 'latches': 'latch', '~produce': '~produce', '~fine': '~fine', 'keep': 'keep', 'abuse': 'abuse', 'pleasured': '', 'daubed': 'daub', 'retain': 'retain', 'stimulate': 'stimulate', 'embarrasses': 'embarrass', 'pitied': 'pity', 'possessing': 'possess', 'confuse': 'confuse', 'reaches': 'reach', 'embarrassed': 'embarrass', 'hurted': 'hurt', 'reached': 'reach', 'blows': 'blow', 'pities': 'pity', 'has': 'have', 'intellectualizes': '', 'automount': '', 'achieved': 'achieve', 'chased': 'chase', 'adopted': 'adopt', 'courted': 'court', 'attack': 'attack', 'eall': '', 'chases': 'chase', 'misunderstood': 'misunderstand', 'interests': 'interest', 'relieving': 'relieve', 'accompany': 'accompany', 'emasculates': 'emasculate', 'punish': 'punish', 'completed': 'complete', '~resent': '~resent', 'applauds': 'applaud', '~loves': '~love', 'repect': '', 'completes': 'complete', 'updating': 'update', 'stumping': 'stump', 'lovee': '', 'observed': 'observe', 'spurn': 'spurn', 'swindled': 'swindle', 'bother': 'bother', 'see': 'see', 'flashed': 'flash', 'humped': 'hump', 'loves': 'love', 'lover': '', 'visited': 'visit', 'waterboarding': '', 'misunderstand': 'misunderstand', 'typecasting': 'typecast', 'clip': 'clip', 'trusting': 'trust', 'buy': 'buy', 'torment': 'torment', 'defending': 'defend', 'have': 'have', 'dictate': 'dictate', 'need': 'need', 'constrained': 'constrain', 'screw': 'screw', 'pursued': 'pursue', 'switch': 'switch', 'for': '', 'provoked': 'provoke', 'awes': 'awe', 'pursues': 'pursue', 'snubs': 'snub', 'lectures': 'lecture', 'deploy': 'deploy', 'weeped': 'weep', 'connected': 'connect', 'amongst': '', 'deny': 'deny', 'gather': 'gather', 'upset': 'upset', 'face': 'face', 'looked': 'look', 'outlive': 'outlive', 'smirked': 'smirk', 'slandered': 'slander', '~govern': '~govern', 'nags': 'nag', 'absorbing': 'absorb', 'text': '', 'pleases': 'please', 'scampered': 'scamper', 'recollects': 'recollect', 'spanking': 'spank', 'connect': 'connect', 'bring': 'bring', 'honnor': '', 'serving': 'serve', 'rejecting': 'reject', 'rebuke': 'rebuke', 'fear': 'fear', 'underappreciated': '', 'debate': 'debate', 'inspiring': 'inspire', 'illumine': 'illumine', 'grabbed': 'grab', 'hops': 'hop', 'endangers': 'endanger', 'credited': 'credit', 'controls': 'control', 'bug': 'bug', 'reminisce': 'reminisce', 'neared': 'near', 'inhabit': 'inhabit', 'jab': 'jab', 'hope': 'hope', 'outsell': 'outsell', 'meant': 'mean', 'doubting': 'doubt', 'slows': 'slow', 'listened': 'listen', 'beat': 'beat', 'unchained': 'unchain', 'generalise': 'generalise', 'sues': 'sue', 'hassled': 'hassle', 'joins': 'join', 'smash': 'smash', 'fooling': 'fool', 'calling': 'call', 'stuff': 'stuff', 'contradicting': 'contradict', 'ministered': 'minister', 'taxed': 'tax', 'fixed': 'fix', 'deceived': 'deceive', '~disappoints': '~disappoint', 'strengthened': 'strengthen', '~beleive': '~', 'expel': 'expel', '~proselytize': '~proselytize', 'caning': 'cane', 'freeze': 'freeze', 'accused': 'accuse', '~deceived': '~deceive', 'bomb': 'bomb', 'exploited': 'exploit', 'insulting': 'insult', 'cried': 'cry', 'tend': 'tend', 'lub': '', 'email': 'email', 'bought': 'buy', 'ken': '', 'spares': 'spare', 'embrace': 'embrace', 'deliver': 'deliver', 'handpicked': '', 'scolds': 'scold', 'interfere': 'interfere', 'kicking': 'kick', 'blinked': 'blink', 'libeling': 'libel', 'shapes': 'shape', 'screamed': 'scream', 'staring': 'stare', 'commands': 'command', 'figured': 'figure', 'outrank': 'outrank', '~follow': '~follow', 'disobeyed': 'disobey', 'drug': 'drug', 'fulfilled': 'fulfil', 'assure': 'assure', 'devour': 'devour', 'conquered': 'conquer', 'invites': 'invite', 'torments': 'torment', 'polymorphs': '', 'teasing': 'tease', 'influencing': 'influence', 'laugh': 'laugh', 'confronts': 'confront', 'quit': 'quit', 'inhale': 'inhale', 'gutpunched': '', 'thanked': 'thank', 'responds': 'respond', 'quiz': 'quiz', 'treat': 'treat', 'recognize': 'recognize', 'choose': 'choose', 'chastised': 'chastise', 'senses': 'sense', 'controlled': 'control', '~invade': '~invade', 'empowering': 'empower', 'swarmed': 'swarm', 'moved': 'move', 'releasing': 'release', 'chastises': 'chastise', 'kicks': 'kick', 'perseveres': 'persevere', 'welcoming': 'welcome', 'abandoned': 'abandon', 'worshipped': 'worship', 'dodge': 'dodge', 'excusing': 'excuse', 'value': 'value', 'owns': 'own', 'promoted': 'promote', 'h8z': '', 'magnetize': 'magnetize', 'loathes': 'loathe', '~abandon': '~abandon', 'offending': 'offend', 'ringing': 'ring', 'tickled': 'tickle', '~told': '~tell', 'nudged': 'nudge', 'berates': 'berate', 'respected': 'respect', 'examined': 'examine', '~escape': '~escape', 'partner': 'partner', 'capture': 'capture', 'moves': 'move', 'steer': 'steer', 'domesticated': 'domesticate', 'cross': 'cross', 'fasinate': '', 'slammed': 'slam', 'gets': 'get', 'coached': 'coach', 'complemented': 'complement', 'shames': 'shame', 'reporting': 'report', 'disagree': 'disagree', 'effect': 'effect', 'censoring': 'censor', 'bullying': 'bully', 'discouraged': 'discourage', 'fucked': 'fuck', 'audit': 'audit', 'off': 'off', 'fascinate': 'fascinate', 'i': '', 'adapted': 'adapt', 'thought': 'think', 'command': 'command', 'gutted': '', 'drowns': 'drown', 'drawing': 'draw', 'restore': 'restore', 'tickles': 'tickle', 'rocket': 'rocket', '~hit': '~hit', 'accosting': 'accost', 'cries': 'cry', 'rocked': 'rock', 'protecting': 'protect', 'detain': 'detain', 'downvoted': '', '~forgives': '~forgive', 'danced': 'dance', 'smite': 'smite', 'console': 'console', 'sickened': 'sicken', 'recommending': 'recommend', 'discuss': 'discuss', 'arresting': 'arrest', 'honouring': 'honour', 'add': 'add', 'propositions': 'proposition', 'terrorizes': 'terrorize', 'match': 'match', 'canter': 'canter', 'soulbound': '', 'nvr': '', 'molding': 'mold', 'taunt': 'taunt', 'loveed': 'love', '~offer': '~offer', 'reads': 'read', 'imed': '', 'press': 'press', 'taking': 'take', 'crushes': 'crush', 'intrigues': 'intrigue', 'like': 'like', 'inviting': 'invite', 'exploiting': 'exploit', 'frustrate': 'frustrate', 'admitted': 'admit', 'taping': 'tape', 'filmed': 'film', 'guise': '', 'lose': 'lose', 'become': 'become', 'works': 'work', 'warmed': 'warm', 'belonged': 'belong', 'hail': 'hail', 'holler': 'holler', 'choosing': 'choose', 'gave': 'give', 'liking': 'like', 'wisecrack': 'wisecrack', 'neglecting': 'neglect', 'scares': 'scare', 'highlighting': 'highlight', 'bet': 'bet', 'lead': 'lead', 'resskilled': '', 'avoid': 'avoid', 'lean': 'lean', '~left': '~leave', 'rewarding': 'reward', 'does': 'do', 'screwed': 'screw', 'chains': 'chain', 'ripped': 'rip', 'obey': 'obey', 'schedule': 'schedule', 'selecting': 'select', '~dislike': '~dislike', 'pressure': 'pressure', 'host': 'host', 'snapped': 'snap', 'startles': 'startle', 'choked': 'choke', 'stay': 'stay', 'slug': 'slug', 'disowning': 'disown', 'gained': 'gain', 'carried': 'carry', 'linger': 'linger', 'withdrew': 'withdraw', 'persuades': 'persuade', 'recognized': 'recognize', 'idolize': 'idolize', 'rammed': 'ram', 'swear': 'swear', 'tailed': 'tail', 'recognizes': 'recognize', 'distressed': 'distress', 'stakes': 'stake', 'h8': '', 'own': 'own', 'detest': 'detest', 'owe': 'owe', 'booed': 'boo', '~hide': '~hide', 'leuch': '', 'fundraises': 'fundraise', 'pitying': 'pity', 'promise': 'promise', 'esteem': 'esteem', 'hitting': 'hit', 'nuke': 'nuke', 'rejoice': 'rejoice', 'rushed': 'rush', 'groomed': 'groom', 'noticed': 'notice', 'recognised': 'recognise', 'resists': 'resist', 'huan': '', 'recruited': 'recruit', 'nourish': 'nourish', 'writhed': 'writhe', 'winked': 'wink', 'directs': 'direct', 'reminds': 'remind', 'hi': '', 'pk': '', 'squeeze': 'squeeze', 'eat': 'eat', 'count': 'count', 'made': 'make', 'wish': 'wish', 'grieve': 'grieve', 'hosting': 'host', 'signed': 'sign', 'convince': 'convince', 'woke': 'wake', 'disinherits': 'disinherit', 'bearing': 'bear', 'humbling': 'humble', 'whisper': 'whisper', 'contribute': 'contribute', 'kisses': 'kiss', 'upsets': 'upset', 'beats': 'beat', 'spanks': 'spank', 'resented': 'resent', 'kissed': 'kiss', 'cuddled': 'cuddle', 'happen': 'happen', 'nursed': 'nurse', 'planting': 'plant', 'babysits': '', 'demonize': 'demonize', 'boot': 'boot', 'repay': 'repay', 'propositioned': 'proposition', 'wander': 'wander', 'stigmatizing': 'stigmatize', 'book': 'book', 'gossip': 'gossip', '~disrespected': '~disrespect', 'importuned': 'importune', 'copyed': 'copy', 'contacting': 'contact', 'iove': '', 'withstood': 'withstand', 'bailing': 'bail', 'nudging': 'nudge', 'raping': 'rape', 'insults': 'insult', 'stab': 'stab', 'kinda': '', 'pacify': 'pacify', 'empowers': 'empower', 'appoint': 'appoint', 'shuns': 'shun', 'rule': 'rule', 'abhor': 'abhor', 'compete': 'compete', 'understand': 'understand', 'yell': 'yell', 'defend': 'defend', 'ticketed': 'ticket'}

root_to_vps_map = {
  'coach': ['coach', 'coached'],
   'consider': ['considered ', 'considers', 'considering', 'consider ', 'consider'],
   'pardon': ['pardon', 'pardon ', 'pardoned'],
   'rob': ['rob', 'robbed '],
   'protest': ['protest', 'protests '],
   'diss': ['dissed ', 'diss'],
   'follow': ['follow', 'followed ', 'followed'],
   'hate': ['hate', 'would hate', 'hated ', 'hates ', 'will hate', 'hated', 'hates', 'hate ', 'must hate'],
   'milk': ['milked ', 'milk', 'milks', 'milking '],
   'glimpse': ['glimpsed', 'glimpse'],
   'adorn': ['adorned ', 'adorn'],
   'excoriate': ['excoriate', 'excoriated '],
   'scold': ['scold', 'scolded', 'scolded ', 'scolds', 'scold ', 'scolds '],
   'send': ['send ', 'sent ', 'sent', 'send'],
   'charge': ['would charge', 'charges ', 'charge', 'should charge ', 'charge ', 'charges', 'charged', 'charged ', 'charging '],
   'compensate': ['compensates ', 'compensated ', 'compensate', 'compensates', 'compensate ', 'must compensate '],
   'swap': ['swap', 'swaps '],
   'dislike': ['dislikes', 'disliked', 'dislike ', 'dislike', 'disliked '],
   'eliminate': ['eliminated', 'eliminate'],
   'pay': ['would pay', 'will pay ', 'could pay ', 'pays', 'pay ', 'paid ', 'paid', 'paying', 'paying ', 'pay', 'pays ', 'should pay'],
   '~fault': ['cannot fault ', "can't fault"],
   'underpay': ['underpay', 'underpay '],
   '~judge': ["don't judge"],
   'smack': ['smack', 'smacks '],
   'mourn': ['mourn', 'mourn '],
   'lynch': ['lynch', 'lynch '],
   'accuse': ['accused ', 'accuse', 'accuses', 'accuse '],
   'begrudge': ['begrudge', 'begrudging ', 'begrudge '],
   'ticket': ['ticket ', 'ticketed ', 'ticket', 'ticketed'],
   'blast': ['blasted', 'blast', 'blast '],
   'peg': ['peg ', 'peg', 'pegs '],
   'prize': ['prize'],
   'marry': ['married ', 'married', 'marry ', 'marry', 'marries'],
   'dig': ['dug ', 'dig ', 'dig'],
   'laud': ['lauded', 'laud', 'laud '],
   'leave': ['leave ', 'leaves', 'left', 'could leave', 'left ', 'leave', 'leaves ', 'leaving'],
   'settle': ['settled', 'settle'],
   'disqualify': ['disqualify', 'disqualify '],
   'challenge': ['challenge ', 'challenges', 'challenge', 'challenged '],
   '~recognize': ['did not recognize', 'not recognize', 'would not recognize'],
   'chew': ['chew', 'chewed'],
   'regret': ['regretted ', 'regret'],
   'discover': ['discover ', 'discover', 'discovered '],
   'sign': ['signed ', 'sign', 'sign ', 'signed'],
   'nail': ['nail', 'nailed ', 'nail '],
   'crave': ['crave', 'craves'],
   'blaspheme': ['blaspheme', 'blasphemes '],
   'even': ['even', 'even irrationally blames '],
   'admire': ['admires ', 'admired', 'admires', 'admire ', 'admired ', 'admire'],
   'sue': ['would sue', 'sue ', 'sued', 'sue', 'should sue ', 'sued ', 'suing ', 'could sue', 'sues'],
   'curse': ['curse', 'curses', 'curse ', 'cursed '],
   'sub': ['subbed', 'sub'],
   'rate': ['rate'],
   'wreck': ['wreck', 'wrecks', 'wrecks '],
   'sadden': ['sadden', 'should sadden'],
   'poison': ['poison'],
   'suspect': ['suspect', 'suspects', 'suspect '],
   'unmask': ['unmasks ', 'unmask', 'unmasked ', 'unmasks'],
   'drill': ['drilling', 'drill'],
   'honour': ['honoured', 'honour', 'honour ', 'honoured '],
   'empower': ['empower', 'empowers'],
   'detest': ['detest', 'detested ', 'detests ', 'detest '],
   'enroll': ['enroll with ', 'enroll'],
   'engage': ['engage ', 'engage'],
   'receive': ['receive ', 'received ', 'receive'],
   'study': ['studied', 'study'],
   'ridicule': ['ridiculed ', 'ridicule', 'ridiculed', 'ridicules '],
   'experience': ['experience'],
   'resurrect': ['resurrected ', 'resurrect'],
   'credit': ['credit', 'credited ', 'credits ', 'credit '],
   'harass': ['harass', 'harass '],
   'smoke': ['smoke', 'smoked '],
   'boo': ['boo', 'boo '],
   'requite': ['requites', 'requite', 'shall requite'],
   'honor': ['honored', 'honors', 'honor ', 'honor', 'honored '],
   'massage': ['massage', 'massaged '],
   '~resent': ["doesn't resent"],
   'elect': ['elect', 'elected '],
   'criticise': ['criticise', 'criticising ', 'criticises', 'criticise '],
   'win': ['win ', 'win'],
   'manage': ['manage ', 'manage'],
   'prefer': ['prefer', 'prefer '],
   'replace': ['replace', 'replaced '],
   'shun': ['shun'],
   'sympathise': ['sympathise', 'sympathises with'],
   'market': ['market', 'market '],
   'use': ['used ', 'using', 'uses ', 'use ', 'used', 'uses', 'use', 'using '],
   'eye': ['eyes', 'eye'],
   'visit': ['visit', 'visited ', 'visit ', 'visits'],
   'insult': ['insult', 'insult '],
   'call': ['call', 'calls ', 'call ', 'called', 'called ', 'call for '],
   'recommend': ['recommend', 'recommended', 'recommend ', 'recommend joining '],
   'tell': ['tells ', 'tell', 'tells', 'tell ', 'told', 'told ', 'tell you thank'],
   'expose': ['expose', 'exposing', 'exposed ', 'exposed', 'expose ', 'exposes', 'exposing ', 'exposes '],
   'award': ['award', 'awards'],
   'hurt': ['hurt', 'hurts '],
   'warn': ['warns', 'warn ', 'warn', 'did warn '],
   'excuse': ['excuse', 'excuse ', 'excused'],
   'warm': ['warm', 'warmed'],
   'hold': ['hold', 'held ', 'held', 'holds ', 'hold '],
   'shoot': ['shoot', 'shot '],
   'join': ['join', 'can join ', 'joined ', 'to join ', 'joining ', 'will join ', 'joined', 'joining', 'join ', 'joins'],
   'room': ['room', 'room he gave '],
   'pursue': ['pursue', 'pursues'],
   'ride': ['ride ', 'ride'],
   'work': ['work', 'worked '],
   'chastise': ['chastise', 'chastised ', 'chastise ', 'chastised'],
   'praise': ['praising', 'praises ', 'praising ', 'praises', 'praised', 'praise ', 'praised ', 'praise'],
   'abandon': ['abandoned ', 'abandon', 'abandoned you once she realized '],
   'meet': ['meet', 'met '],
   'arrive': ['arrive', 'arrived to thank '],
   'control': ['control', 'controlled'],
   'claim': ['claim', 'claimed'],
   'tap': ['tap', 'tapped'],
   'give': ['give', 'give thanks to', 'gave', 'can give ', 'gives', 'give ', 'giving ', 'gave into ', 'gave ', 'given '],
   'lock': ['locks ', 'lock'],
   'tax': ['tax ', 'tax'],
   'fuck': ['fucking hated', 'fuck'],
   'accept': ['accepted ', 'accepts ', 'accept ', 'accepts', 'can accept ', 'accepted', 'would accept ', 'accept', 'might accept', 'will accept', 'do accept'],
   'want': ['wanted to say was a big thank you to', 'want', 'wants ', 'wanted to encourage ', 'want ', 'wants', 'want to pay ', 'wanted', 'want to thank ', 'wanted '],
   'sense': ['sensed ', 'sense'],
   'reprove': ['reproved', 'reprove'],
   'condemn': ['condemn ', 'condemned', 'condemns', 'condemning', 'condemn', 'condemning ', 'Condemn ', 'condemned '],
   'provide': ['provide', 'provided ', 'provided', 'provides'],
   'comfort': ['comforted', 'comfort'],
   'utilize': ['utilize', 'utilized', 'utilized '],
   'write': ['wrote ', 'wrote', 'write', 'writes '],
   '~pardon': ['cannot pardon '],
   'reject': ['rejects', 'rejected', 'reject ', 'rejected ', 'will reject ', 'rejects ', 'reject'],
   'answer': ['answer', 'answered '],
   'place': ['place', 'place ', 'placed'],
   'loathe': ['loathe', 'loathe ', 'loathed', 'loathes'],
   'deplore': ['deplored ', 'deplore'],
   'stop': ['stop billing', 'stop seeing ', 'stopped stocking ', 'stop', 'stopped '],
   'spot': ['spotted ', 'spot', 'spotted', 'spots '],
   'denounce': ['denounce ', 'denounce', 'denounces ', 'denounced '],
   'abuse': ['abusing', 'abuse', 'abused '],
   'lay': ['lay', 'lays into '],
   'suck': ['sucks ', 'suck'],
   'grow': ['grow', 'grew up prepared '],
   '~curse': ['not curse'],
   'criticize': ['criticize ', 'criticizes', 'criticized', 'would criticize', 'criticizing', 'criticize', 'criticized ', 'criticizes '],
   'remember': ['remembering ', 'remember', 'remember ', 'remembers', 'remembered'],
   'register': ['register'],
   'appreciate': ['appreciate', 'appreciated ', 'appreciated', 'appreciate ', 'appreciates', 'would appreciate', 'appreciates '],
   'greet': ['greet', 'greets '],
   'disembowel': ['disembowel', 'disemboweled'],
   'inform': ['informed', 'inform'],
   'allow': ['allows ', 'allow'],
   'suggest': ['suggest', 'suggested '],
   'retaliate': ['retaliate'],
   'refund': ['refunded ', 'will refund ', 'refund', 'refund ', 'refunded', 'will refund'],
   'help': ['help', 'help '],
   'deck': ['deck'],
   'move': ['moved ', 'move ', 'move'],
   'trade': ['trade', 'trade ', 'traded '],
   'equip': ['equip', 'equips ', 'equipping ', 'equips', 'equip '],
   'strangle': ['strangle', 'strangle '],
   'still': ['still hate', 'still hate ', 'still', 'still respected', 'still resented ', 'still blame ', 'still hated ', 'still owe', 'still resents'],
   'worship': ['worship', 'worships', 'worship '],
   'style': ['style', 'styled'],
   'thank': ['would thank', 'thanks', 'thank ', 'Thanked ', 'thanking', 'thank', 'will thank ', 'must thank', 'thanked ', 'to thank ', 'should thank ', 'could thank', 'thanking ', 'thanks ', 'thanked', 'can thank '],
   'fit': ['fitting ', 'fitted', 'fit', 'fitted '],
   'acknowledge': ['acknowledges', 'acknowledge ', 'acknowledge', 'acknowledges ', 'acknowledged '],
   'pray': ['praying with', 'pray'],
   'choose': ['chooses', 'choose ', 'chooses ', 'chose', 'choose', 'chose '],
   'mail': ['mail'],
   'petition': ['petition', 'petition '],
   'glorify': ['glorify', 'glorify '],
   'evaluate': ['evaluate ', 'evaluate'],
   '~marry': ['cannot marry '],
   'propose': ['proposed', 'propose'],
   'slate': ['slate', 'slate '],
   'idolise': ['idolises ', 'idolise'],
   'interview': ['interview', 'interviewed', 'interview ', 'interviewed '],
   'kiss': ['kiss', 'kissed'],
   'belittle': ['belittle ', 'belittle'],
   'realize': ['realize', 'realized '],
   'assess': ['assessed ', 'assess'],
   'execute': ['execute ', 'execute'],
   'name': ['name', 'name ', 'named '],
   'drop': ['dropped ', 'drops ', 'drop', 'drop '],
   'feast': ['feasted ', 'feast'],
   'absolve': ['absolve', 'absolved ', 'absolved'],
   'bless': ['blessed', 'blesses', 'bless', 'blesses ', 'bless '],
   'roast': ['roast', 'roasted ', 'roast '],
   'found': ['found ', 'found'],
   'revere': ['revere', 'revere ', 'reveres'],
   'shock': ['shock', 'shocked '],
   'castigate': ['castigate ', 'castigate'],
   'orient': ['orient', 'orients '],
   'whip': ['whip ', 'whip', 'whipped '],
   'out': ['outing', 'out', 'outed'],
   'try': ['tried ', 'try'],
   'defend': ['defend ', 'defends', 'defend'],
   'encourage': ['encourage', 'encouraged '],
   'lecture': ['lecture', 'lectures'],
   'salute': ['salute', 'salute '],
   'maneuver': ['maneuvers', 'maneuver'],
   'bully': ['bully', 'bullying '],
   'sympathize': ['sympathize', 'sympathize with'],
   'jilt': ['jilted ', 'jilted', 'jilt'],
   'forgive': ['forgives ', 'shall forgive ', 'will forgive', 'forgave ', 'will forgive ', 'might forgive', 'do forgive', 'forgiven ', 'can forgive ', 'could forgive', 'to forgive', 'forgive', 'to forgive ', 'could forgive ', 'does forgive', 'forgave', 'must forgive', 'should forgive', 'can forgive', 'forgives', 'forgiven', 'forgive '],
   'undo': ['undo'],
   'disrespect': ['disrespect', 'disrespects'],
   'release': ['release', 'released'],
   'reason': ['reason', 'reason he asked '],
   'upbraid': ['upbraids ', 'upbraid'],
   'censure': ['censures', 'censured ', 'censure'],
   'ask': ['asked', 'asks', 'ask ', 'could ask ', 'asking ', 'ask', 'would ask', 'asks ', 'asked '],
   'teach': ['taught ', 'teach'],
   'reproach': ['reproached ', 'reproaches ', 'reproach', 'reproached', 'reproaches'],
   'bash': ['bash ', 'bash', 'bashed ', 'bashing '],
   'keep': ['keep exposing', 'keep', 'keep ', 'kept', 'kept ', 'kept billing'],
   'oppose': ['oppose', 'oppose '],
   'recompense': ['recompensed ', 'might recompense', 'recompense', 'recompense '],
   'preach': ['preached to', 'preach'],
   'think': ['think', 'think of', 'thought represented'],
   'excommunicate': ['excommunicate ', 'excommunicate'],
   'feed': ['feeding', 'fed ', 'feed ', 'feed', 'fed'],
   'enjoy': ['enjoy', 'enjoying ', 'enjoyed', 'enjoyed ', 'enjoy ', 'should enjoy '],
   'suspend': ['suspend ', 'suspends', 'suspend'],
   'feel': ['feel has prepared ', 'feel like it prepared ', 'feel', 'feel suits', 'feel '],
   'sack': ['sack', 'sack '],
   'pop': ['popped ', 'pop'],
   'carry': ['carry ', 'carries ', 'carry'],
   'demote': ['demoted', 'demote'],
   'ditch': ['ditch', 'ditch ', 'ditched ', 'ditched', 'ditches '],
   'miss': ['missed ', 'miss ', 'miss'],
   'pledge': ['pledged', 'pledge'],
   'bite': ['bites', 'bites ', 'bite'],
   'attack': ['attacking ', 'attacked ', 'would attack ', 'attacked', 'attack ', 'attacks', 'attacks ', 'attacking', 'attack'],
   'draft': ['draft', 'drafted '],
   'persecute': ['persecute', 'persecuted', 'persecuted '],
   'cuff': ['cuff', 'cuff '],
   'cite': ['cite ', 'cited ', 'cite'],
   'lambaste': ['lambasted ', 'lambaste'],
   'hug': ['hug', 'hugged '],
   'accompany': ['accompanied', 'accompany'],
   'punish': ['punish ', 'punishes ', 'punishing ', 'punishes', 'punished', 'punished ', 'punishing', 'punish'],
   'acquire': ['acquire them and they pay ', 'acquire'],
   'serve': ['serve', 'serve ', 'served'],
   'believe': ['believe ', 'believe', 'believed '],
   'spurn': ['spurn', 'spurned '],
   'target': ['target', 'target ', 'targeted ', 'targeted'],
   'lament': ['lamented ', 'lamented', 'lament'],
   'nominate': ['nominate', 'nominated', 'nominate ', 'nominated '],
   'require': ['require', 'required'],
   'beg': ['beg', 'begs', 'begged'],
   'project': ['Project Gutenberg Consortia Center, ... He scolded ', 'project'],
   'medicate': ['medicate', 'medicated '],
   'stalk': ['stalk', 'stalked'],
   'sedate': ['sedate', 'sedate '],
   'crucify': ['would crucify', 'crucified', 'crucifying', 'crucify'],
   'strengthen': ['strengthens ', 'strengthen', 'strengthen '],
   '~believe': ['cannot believe I volunteered '],
   'say': ['say', 'say bless ', 'said may disqualify ', "say 'thank you' to", 'say thank ', 'say thank you to'],
   'slam': ['slam', 'slammed ', 'slams ', 'slams', 'slammed'],
   'have': ['had forgiven ', 'had asked', 'had contacted', 'had with ', 'would have qualified', 'should have thanked', 'has', 'had thanked ', 'had arranged for ', 'has forgiven ', 'have forgiven ', 'has prepared', 'had to respect', 'had accepted', 'have paid', 'has ', 'had to revive him and they prepared ', 'had dogs chasing ', 'had forgiven', 'have seen ', 'has admired', 'have refunded', 'could have prepared her', 'had paid ', 'have ', 'have', 'had '],
   'need': ['needed', 'needed just', 'needed ', 'needs ', 'needs', 'need ', 'need to say "thank you" to', 'need'],
   'seek': ['seek ', 'seek', 'sought '],
   'sell': ['sell ', 'sold ', 'sell', 'sold'],
   'screw': ['screws ', 'screw'],
   'soak': ['soak ', 'soak'],
   'isolate': ['isolate', 'isolated '],
   'take': ['took', 'take', 'would take', 'took ', 'takes', 'take ', 'takes ', 'taking'],
   'destroy': ['destroy', 'destroy '],
   'begin': ['begin', 'began interviewing '],
   'apprize': ['apprize', 'apprize '],
   'reckon': ['reckon', 'reckons '],
   'quote': ['quoted', 'quoted ', 'quote'],
   'reach': ['reach', 'reach '],
   'educate': ['educating', 'educate'],
   'reverence': ['reverences ', 'reverence'],
   'deny': ['denied', 'deny ', 'deny'],
   'seize': ['seize', 'seized'],
   'clock': ['clocked', 'clocked ', 'clock'],
   'cover': ['cover ', 'cover'],
   'face': ['faces', 'face'],
   'axe': ['axe'],
   'incarcerate': ['incarcerate ', 'incarcerate'],
   'despise': ['despised', 'despises', 'despise ', 'despises ', 'despise', 'despised '],
   'show': ['showed ', 'shows ', 'showed', 'shown', 'shows', 'show ', 'show', 'showing'],
   'probe': ['probes ', 'probe'],
   'terminate': ['terminate', 'terminate '],
   'bring': ['bring ', 'brought with ', 'brought ', 'bring'],
   '~dump': ['should not dump '],
   'rebuke': ['rebuked ', 'rebuke ', 'rebuked', 'rebuke'],
   'fear': ['feared', 'feared ', 'fears', 'fear'],
   'fine': ['fine ', 'fine', 'fined '],
   'find': ['finds ', 'find', 'find '],
   'ground': ['ground', 'grounded ', 'ground '],
   'toast': ['toast', 'toast '],
   'envy': ['envies ', 'envy ', 'envies', 'envied', 'envy', 'envied '],
   'treasure': ['treasured ', 'treasure', 'treasure '],
   'pump': ['pump', 'pump '],
   'bust': ['busting', 'bust', 'busted '],
   'bug': ['bug'],
   'betray': ['betrays ', 'betrayed ', 'betray'],
   'disgust': ['disgusted', 'disgust'],
   'announce': ['announce', 'announced '],
   'hope': ['hope you like', 'hope prepares ', 'hope they kill', 'hope'],
   'dispute': ['dispute', 'disputes '],
   'prosecute': ['prosecuted', 'prosecute ', 'prosecute'],
   'affirm': ['affirm', 'affirmed ', 'affirm '],
   'hit': ['hits ', 'hit', 'hit '],
   'get': ['got', 'gets ', 'would get mad at', 'got ', 'get', 'gets', 'get '],
   'beat': ['beat', 'beat '],
   'watch': ['watches ', 'watch', 'watch ', 'watched '],
   'perceive': ['perceive', 'perceived ', 'perceive '],
   'resent': ['resent ', 'resents', 'resented ', 'resents ', 'resent', 'resented'],
   'report': ['report ', 'reported', 'report', 'reported '],
   'celebrate': ['celebrated ', 'celebrate ', 'celebrate'],
   'reveal': ['revealed', 'reveal', 'reveals', 'reveal ', 'reveals ', 'revealed '],
   'pimp': ['pimp', 'would pimp slap', 'pimped'],
   'ordain': ['ordained', 'ordain'],
   'remove': ['removed ', 'removed', 'remove'],
   'summon': ['summoned', 'summon', 'summoned '],
   'bag': ['bag ', 'bag', 'bagged'],
   'ban': ['ban ', 'banned ', 'ban', 'banned', 'bans '],
   'uncover': ['uncovered', 'uncover'],
   'grab': ['grab ', 'grabbed', 'grab'],
   '~blame': ["can't blame ", "don't blame", "can't blame", "didn't blame"],
   'view': ['view ', 'view', 'viewed '],
   'set': ['set', 'set '],
   'dump': ['dump ', 'dumps', 'dumped', 'dumped ', 'dumps ', 'dump'],
   'frame': ['framed', 'frame'],
   'recruit': ['recruit', 'recruited ', 'recruited'],
   'see': ['must see', 'sees', 'seen', 'see ', 'sees ', 'seen ', 'do see', 'see', 'seeing ', 'seeing', 'can see'],
   'fail': ['fail to recognize', 'fail', 'fail ', 'failed '],
   'hammer': ['hammer', 'hammer '],
   'lapidate': ['lapidate ', 'lapidate'],
   'vilify': ['vilify ', 'vilify'],
   'analyze': ['analyze', 'analyzed '],
   'please': ['please convey a big thank you to ', 'please'],
   'label': ['labeled ', 'labels', 'label'],
   'misjudge': ['misjudge ', 'misjudge'],
   'scorn': ['scorn'],
   'flame': ['flamed ', 'flame'],
   'approach': ['approached ', 'approach ', 'approach'],
   'email': ['email'],
   'compliment': ['complimented', 'compliment ', 'compliment'],
   'preserve': ['preserve', 'preserve '],
   'blame': ['would blame', 'blame ', 'blames', 'blamed', 'blame', 'can blame ', 'blames ', 'blamed ', 'blaming', 'blaming '],
   'overcharge': ['overcharged ', 'overcharge'],
   'spoil': ['spoiled ', 'spoil'],
   'come': ['did come to forgive', 'come'],
   'monitor': ['monitors ', 'monitor'],
   'pity': ['pity', 'pity ', 'pitied ', 'pitied'],
   'fault': ['faults ', 'fault ', 'fault', 'faulted ', 'could fault '],
   'admit': ['admit', 'admitted'],
   'delete': ['deleted', 'delete'],
   'approve': ['approve ', 'approve'],
   'evict': ['evict', 'evict '],
   'spank': ['spanked ', 'spanks ', 'spank', 'spank '],
   'commend': ['commended ', 'commend ', 'commends', 'commends ', 'commended', 'commend'],
   'exploit': ['exploit', 'exploit '],
   'indict': ['indict ', 'indicts ', 'indict'],
   'cancel': ['cancel ', 'cancel'],
   'respect': ['should respect', 'should respect ', 'respects ', 'respected ', 'respects', 'respect ', 'respect', 'respected'],
   'trust': ['trust', 'trusted', 'trust ', 'trusts '],
   'assign': ['assign', 'assigns '],
   'penalize': ['penalize', 'penalize ', 'penalizes '],
   'raise': ['raised ', 'raise'],
   'create': ['created ', 'created', 'create'],
   'overlook': ['overlook ', 'overlook'],
   'quiz': ['quizzed', 'quiz'],
   'damn': ['damn', 'should damn'],
   'treat': ['treat ', 'treats', 'treated ', 'treating', 'treated', 'would treat', 'treat'],
   'threaten': ['threatened', 'threatens ', 'threatens', 'threaten'],
   'fry': ['fry ', 'fry'],
   'waste': ['waste', 'wasted '],
   'define': ['defined', 'define ', 'define'],
   'fire': ['fired', 'fire ', 'fired ', 'fire'],
   'reimburse': ['reimburse', 'reimbursed', 'reimburses', 'reimbursed ', 'reimburse '],
   'dismiss': ['dismiss', 'dismissed ', 'dismiss '],
   'fund': ['fund'],
   'observe': ['observe ', 'observe'],
   'understand': ['understood ', 'understands ', 'understands', 'understand'],
   'slap': ['slaps ', 'slap', 'slap ', 'slapped'],
   'catch': ['catch ', 'caught ', 'catch', 'caught'],
   'present': ['present ', 'present'],
   'volunteer': ['volunteered ', 'volunteer'],
   'sanctify': ['sanctified', 'sanctifies', 'sanctify'],
   'intimidate': ['intimidate', 'intimidating'],
   'bill': ['bill', 'bills ', 'will bill ', 'billing', 'billing ', 'bill ', 'bills', 'billed '],
   'tolerate': ['tolerated ', 'tolerate'],
   'value': ['value ', 'valued', 'values', 'valuing', 'values ', 'value'],
   'employ': ['employed ', 'employ', 'employed'],
   'pace': ['pace ', 'pace'],
   'guide': ['guide'],
   'mistake': ['mistake', 'mistaken ', 'mistook ', 'mistakes ', 'mistook', 'mistakes', 'mistake '],
   'rip': ['ripped ', 'rip', 'rip ', 'ripped'],
   'embrace': ['embrace', 'embrace ', 'embraced '],
   '~like': ["won't like"],
   'portray': ['portray ', 'portray', 'portrayed '],
   'doctor': ['doctor', 'doctored '],
   'saw': ['saw ', 'saw'],
   'make': ['make sure to say thank you to', 'make', 'made ', 'make ', 'made'],
   'pester': ['pester', 'pester '],
   'cross': ['cross ', 'cross'],
   'discredit': ['discredit', 'discredited '],
   'taunt': ['taunted', 'taunt'],
   'finish': ['finished ', 'finish'],
   'applaud': ['applauded ', 'applauds ', 'applaud', 'applauded', 'applaud ', 'applauds'],
   'pick': ['picked ', 'picks ', 'pick', 'pick ', 'picks', 'picked'],
   'hang': ['hang', 'hang '],
   'kill': ['will kill', 'killed', 'killed ', 'killing', 'kill', 'kill ', 'kills', 'might kill ', 'would kill'],
   'lambast': ['lambasts', 'lambast'],
   'break': ['break', 'broke up with'],
   'dock': ['docked ', 'docked', 'dock'],
   'humble': ['humble', 'humbling'],
   'berate': ['berate', 'berates ', 'berate ', 'berated', 'berates', 'berated '],
   '~forgive': ['not forgive', "won't forgive", 'cannot forgive', "can't forgive", "don't forgive", 'cannot forgive '],
   'contact': ['contact', 'contact ', 'contacted '],
   'position': ['position ', 'position'],
   'reward': ['rewarded', 'rewards ', 'reward ', 'rewards', 'will reward', 'reward', 'rewarded ', 'should reward ', 'should reward', 'rewarding'],
   'parody': ['parodied', 'parody'],
   'sentence': ['sentence', 'sentenced '],
   '~admire': ["don't admire"],
   'judge': ['judges', 'judged', 'judge ', 'judge', 'judging', 'judging ', 'should judge ', 'judges ', 'judged '],
   'select': ['selects ', 'selected', 'select ', 'selected ', 'select'],
   'identify': ['identify', 'identifying', 'identify ', 'identified ', 'identified'],
   'touch': ['touch', 'touched '],
   'love': ['loving', 'loved ', 'do love', 'loves ', 'love', 'will love', 'love ', 'loved', 'loves', 'loving '],
   'discipline': ['discipline ', 'discipline', 'disciplines '],
   'cut': ['cut', 'cut '],
   'except': ['excepted ', 'except ', 'except'],
   'bench': ['benched ', 'bench'],
   'arrest': ['arrested', 'arrested ', 'arrest ', 'arrest'],
   'save': ['saves', 'saved', 'save ', 'saving', 'save'],
   'match': ['match', 'match '],
   'ream': ['ream', 'reamed '],
   'rejoin': ['rejoin', 'rejoined'],
   '~hold': ["shouldn't hold"],
   'know': ['know it frightens ', 'will know', 'knew', 'know has qualified ', 'know ', 'knows', 'knows he needs', 'knowing', 'knew ', 'must know', 'knows ', 'know'],
   'supervise': ['supervised', 'supervise'],
   'press': ['pressed', 'pressed ', 'press ', 'presses', 'press'],
   'knock': ['knock ', 'knocks ', 'knock'],
   'like': ['liking ', 'likes ', 'do like ', 'liked ', 'likes', 'like ', 'liked', 'like'],
   'confront': ['confront', 'confronted ', 'confront '],
   'hunt': ['hunt', 'hunting'],
   'clown': ['clowned ', 'clown'],
   'ignore': ['ignoring ', 'ignore', 'ignored'],
   'remind': ['remind', 'reminds'],
   'lose': ['lost ', 'lose ', 'lose'],
   'envision': ['envision', 'envision '],
   'sanction': ['sanction', 'sanction '],
   'play': ['playing', 'played ', 'play', 'plays'],
   'hail': ['hailed ', 'hail'],
   'advertise': ['advertise', 'advertises '],
   'congratulate': ['congratulates ', 'congratulate', 'congratulated', 'congratulates', 'congratulate ', 'congratulated '],
   'avoid': ['avoids', 'avoid ', 'avoid', 'avoids ', 'avoided '],
   'cast': ['cast', 'cast ', 'casted '],
   'allocate': ['allocate', 'allocate '],
   'convict': ['convict', 'convicted '],
   'prod': ['prodded ', 'prod'],
   'forbid': ['forbid'],
   'refer': ['referred ', 'referred', 'refer'],
   'be': ['were praising', 'were hating ', 'was using', 'are treating', 'were monitoring ', 'was thanking ', 'were treating ', 'is playing ', 'was preparing', 'were thanking ', 'is selling ', 'were considering ', 'be', 'were criticizing', 'is blaming ', 'am proud of ', 'should be rewarding', 'are seeing '],
   'realise': ['realise ', 'realise'],
   'schedule': ['scheduled', 'scheduled ', 'schedules ', 'schedule'],
   'burn': ['burn ', 'burns', 'burn'],
   'assemble': ['assembled ', 'assemble'],
   'bury': ['bury', 'bury '],
   'slug': ['slugged ', 'slug'],
   'stone': ['stoned ', 'stone'],
   'tease': ['teased', 'teases', 'tease', 'teased '],
   'jeer': ['jeers to', 'jeer'],
   'choke': ['choke', 'would choke'],
   'idolize': ['idolized ', 'idolize ', 'idolize'],
   'cherish': ['cherish', 'cherishes', 'cherished', 'cherish '],
   'block': ['blocked', 'block'],
   'own': ['owns ', 'owns', 'own'],
   'owe': ['owes ', 'owed ', 'do owe', 'owed', 'owes', 'owe ', 'owe'],
   'ensue': ['ensues ', 'ensue'],
   'administer': ['administered ', 'administer'],
   'promise': ['promised ', 'promise'],
   'apologize': ['apologize ', 'apologize'],
   'rely': ['rely', 'rely on '],
   'prepare': ['prepared ', 'could to prepare ', 'preparing ', 'prepare', 'preparing', 'could prepare', 'will prepare', 'prepare ', 'prepared', 'prepares', 'to prepare', 'prepares '],
   '~charge': ['did not charge ', "won't charge", "didn't charge"],
   'support': ['supports ', 'support', 'supported ', 'support ', 'supported'],
   'chide': ['chided ', 'chided', 'chide'],
   'fight': ['fight', 'fought'],
   'start': ['started treating ', 'started charging', 'started seeing', 'started hating ', 'start', 'start judging ', 'can start enjoying '],
   '~hate': ['does not hate', 'not hate ', "won't hate"],
   'suit': ['suit', 'suits'],
   'condone': ['condone', 'condone '],
   'buy': ['buy ', 'bought ', 'buy'],
   'invite': ['invite', 'invite ', 'invites'],
   'bore': ['bore', 'bore '],
   'offer': ['offer', 'offer ', 'offered'],
   'admonish': ['admonishing', 'admonish'],
   'hear': ['hear', 'heard', 'hear ', 'heard '],
   'promote': ['promote', 'promoted ', 'promote '],
   '~mistake': ['do not mistake'],
   'humiliate': ['humiliate', 'humiliate '],
   'hire': ['did hire ', 'hiring', 'hire', 'hiring ', 'hire ', 'hires', 'hired', 'hired '],
   'bargain': ['bargain', 'bargained with '],
   'overpay': ['overpaying', 'overpaying ', 'overpay', 'overpay '],
   'adore': ['adore', 'adored ', 'adore ', 'adores', 'adored', 'adores '],
   'reprimand': ['reprimanded', 'reprimand', 'reprimanded '],
   'appraise': ['appraise ', 'appraise'],
   'pin': ['pinned ', 'pin'],
   'recognize': ['would recognize', 'recognizing', 'to recognize', 'do recognize', 'recognize', 'recognized ', 'recognize ', 'recognized', 'recognizes', 'recognizes '],
   'twist': ['twisted', 'twist'],
   'examine': ['examine', 'examined ', 'examine '],
   'hound': ['hounded', 'hound', 'hound '],
   'mold': ['mold', 'molded'],
   'check': ['check', 'checked', 'check '],
   'film': ['films', 'film', 'filmed'],
   'deserve': ['deserve', 'deserves '],
   'nick': ['nick', 'nicked'],
   'book': ['booked', 'booked ', 'book ', 'book'],
   '~scold': ["didn't scold"],
   'test': ['test', 'tested', 'tested ', 'test '],
   'trash': ['trash'],
   'mock': ['mock ', 'mocks', 'mocked ', 'mock'],
   'intend': ['intend', 'intended'],
   'lend': ['lend', 'lent'],
   'welcome': ['welcome ', 'welcome'],
   'recognise': ['recognises', 'recognised', 'recognise ', 'recognised ', 'recognise', 'recognises '],
   'desert': ['deserted ', 'desert'],
   'appoint': ['appointed ', 'appoint'],
   'grudge': ['grudge ', 'grudge'],
   '~retaliate': ['cannot retaliate against'],
   'groom': ['groom', 'groomed'],
   'rule': ['ruled ', 'rule'],
   'repay': ['repaid ', 'repay', 'repays ', 'will repay', 'repaid', 'repay ', 'repays'],
   'train': ['train ', 'trains', 'training ', 'train'],
   'bribe': ['bribe ', 'bribe'],
   'push': ['push', 'pushed ', 'push ', 'pushed'],
   'wake': ['woke ', 'wake', 'wakes ', 'waked'],
   'yell': ['yelled at ', 'yell'],
   'abhor': ['abhorred ', 'abhor']
 }
